{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-events/3.0.2/ktor-events-3.0.2.module",
    "group": "io.ktor",
    "module": "ktor-events",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-3.0.2.jar",
          "url": "ktor-events-jvm-3.0.2.jar",
          "size": 6396,
          "sha512": "a11bc0f3703caccdfaec537944b05bac8c2b4d3d734e09c36ea0ce3b80aebf62c4b091f901cfcb1df357238be22336089397682ce30b784572632fc7a3801bbe",
          "sha256": "108a99b4dad3d79ca113ea2343a0769dfc77d147b85ebecd3d16b74b4ed3fb9b",
          "sha1": "7e3a1d2617cf9a6f41e53656b0b586dcf2f726cb",
          "md5": "0b63affa862ac5aa54ff2b1522919150"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-3.0.2.jar",
          "url": "ktor-events-jvm-3.0.2.jar",
          "size": 6396,
          "sha512": "a11bc0f3703caccdfaec537944b05bac8c2b4d3d734e09c36ea0ce3b80aebf62c4b091f901cfcb1df357238be22336089397682ce30b784572632fc7a3801bbe",
          "sha256": "108a99b4dad3d79ca113ea2343a0769dfc77d147b85ebecd3d16b74b4ed3fb9b",
          "sha1": "7e3a1d2617cf9a6f41e53656b0b586dcf2f726cb",
          "md5": "0b63affa862ac5aa54ff2b1522919150"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-events-jvm-3.0.2-sources.jar",
          "url": "ktor-events-jvm-3.0.2-sources.jar",
          "size": 2061,
          "sha512": "f1b51ed3a8257771f1517f5825f3030f99e9d2bce44ce45df425bfa669af9384c25c32642af95492642ebba606eece55588e79776305404e7dd505c2aa05cf78",
          "sha256": "db9ffe0a31869e626e495a36e17d93d6e7979ac98727b843bc55b9390487b050",
          "sha1": "d6e358b9bfd0b95d7fcd4f90355768cdad352069",
          "md5": "9023d93195542a2162af7d8c15b072ff"
        }
      ]
    }
  ]
}
