{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences/1.1.1/datastore-preferences-1.1.1.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-release.aar",
          "url": "datastore-preferences-android-1.1.1.aar",
          "size": 16726,
          "sha512": "19518a4096ca2112e621f2adacc7d0c4999cc85a3a02d255fdd49cad7d34b52a24b7033a50f227f0c5ed38acc48a49fe2cdf580fe84f43b5b3713ecd8db577cd",
          "sha256": "0f15760838ff0413521ab1596e8ac5c999c3822d1fcc3f38ce6d6f562aeebbac",
          "sha1": "927dbd4a74ba99501b1d879a22fa6fda1111d01e",
          "md5": "6ed253962a8b8e7fc72f553f432970bd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-release.aar",
          "url": "datastore-preferences-android-1.1.1.aar",
          "size": 16726,
          "sha512": "19518a4096ca2112e621f2adacc7d0c4999cc85a3a02d255fdd49cad7d34b52a24b7033a50f227f0c5ed38acc48a49fe2cdf580fe84f43b5b3713ecd8db577cd",
          "sha256": "0f15760838ff0413521ab1596e8ac5c999c3822d1fcc3f38ce6d6f562aeebbac",
          "sha1": "927dbd4a74ba99501b1d879a22fa6fda1111d01e",
          "md5": "6ed253962a8b8e7fc72f553f432970bd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-android-1.1.1-sources.jar",
          "url": "datastore-preferences-android-1.1.1-sources.jar",
          "size": 6984,
          "sha512": "5eabb487947ffc833882d88065c284933a0c470c87462c2564c73c3b33871ee1521bb056b34cb958f8479d5088233b68651d82dd05ebad38c830a35929b94775",
          "sha256": "c66873f4fd455388d75d7d2bb82503b73de6930e7ed5702b1900754300185938",
          "sha1": "e9aaf8b9d55f6d7e905cf89d502fe80ec60b01b5",
          "md5": "053232850360012cfbf18eb3c3f32517"
        }
      ]
    }
  ]
}