{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-1.1.1-multiplatform-sources.jar",
          "url": "datastore-preferences-core-1.1.1-multiplatform-sources.jar",
          "size": 21352,
          "sha512": "1d632f050d04e360078afdf49d36eb6920f0c17d220530152df3f71509f7654aee760e8f477e944214827ae76ef7f93ca5809299b408169fcbe128156568cd5d",
          "sha256": "4e18d8bdcc96dc52bfd7bbbe2baf6a8d5d89cbddd360cd670ab03e5f5d50ef9f",
          "sha1": "6c0875b8da34da98b6e6d9b228da938f0bb956af",
          "md5": "8bc24099033a11a213179ce2e180f63c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "datastore-preferences-core-1.1.1-versionMetadata.json",
          "size": 5448,
          "sha512": "b0d093cadfad374802c3711d02921f1616942ad4131d5e0c284234104ac4c7cf24036936d65054bce800f33d37c878545ee276e168d21410c743e2c341a7739e",
          "sha256": "812d4bfd874ba50c807014a71a9c8203084c95fcd8c4a578c0e2a22dd7ce0ebe",
          "sha1": "682ee482867a2f565c322320c306a7a8437d6583",
          "md5": "623d9bd2d3ce7472ba2d1bacfb5e3224"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-metadata-1.1.1.jar",
          "url": "datastore-preferences-core-1.1.1.jar",
          "size": 12977,
          "sha512": "1b1eaef7277d884dcb2ed2a193908e341ff6962ecf103642c2cf293ede35ca143a0e424189d2e1fd87e3d3ecbd31af65467ee2ca5f95120e740d359c0b0eb04b",
          "sha256": "a22a84cf98bb1f1b04edc3ff2a4a5f3a273205c773c14d008618c9e2501e440b",
          "sha1": "d78cb0017419d01858806524bb9f8406ecde47f9",
          "md5": "b2c0c2464be2b513c9eb3a12449d3d0d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-kotlin-1.1.1-sources.jar",
          "url": "datastore-preferences-core-1.1.1-sources.jar",
          "size": 15783,
          "sha512": "6e303d42daeea6e053eb60e533238358a434911e155a111cc52d429aeb4de33b782cab9059a9586b9c825ef48fa874df4ecaffc8e1f1519c3ece477f68df1ecb",
          "sha256": "7e2d236cfd000e3dfa228895f30b2656b92f5d18873f4338869c5b43a0e326f5",
          "sha1": "d93aa4d263838c10c42ac6dd2a5f97c83e372f7d",
          "md5": "a35dd5d2166e205d5bf6a19311caffb1"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.1/datastore-preferences-core-iosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.1/datastore-preferences-core-iosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.1.1/datastore-preferences-core-iosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.1/datastore-preferences-core-iossimulatorarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.1/datastore-preferences-core-iossimulatorarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.1.1/datastore-preferences-core-iossimulatorarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.1/datastore-preferences-core-iosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.1/datastore-preferences-core-iosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.1.1/datastore-preferences-core-iosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.1/datastore-preferences-core-jvm-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.1/datastore-preferences-core-jvm-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.1.1/datastore-preferences-core-jvm-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.1.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxx64/1.1.1/datastore-preferences-core-linuxx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxx64/1.1.1/datastore-preferences-core-linuxx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.1/datastore-preferences-core-macosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.1/datastore-preferences-core-macosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.1.1/datastore-preferences-core-macosarm64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.1/datastore-preferences-core-macosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.1/datastore-preferences-core-macosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.1.1/datastore-preferences-core-macosx64-1.1.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.1.1"
      }
    }
  ]
}