--
-- Lion Reader Database Schema
-- Generated by: pnpm db:schema
--
-- This file is auto-generated from the current database state.
-- It provides a snapshot of the schema for reference and review.
-- Do not edit manually - changes should be made via migrations.
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

CREATE TYPE public.feed_type AS ENUM (
    'web',
    'email',
    'saved',
    'collection'
);

CREATE TYPE public.websub_state AS ENUM (
    'pending',
    'active',
    'unsubscribed'
);

CREATE FUNCTION public.apply_membership_changes(p_sign integer, p_user uuid[], p_entry uuid[], p_sub uuid[]) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF p_user IS NULL THEN
    RETURN;
  END IF;
  PERFORM apply_unread_memberships(array_agg(p_sign), array_agg(c.user_id), array_agg(c.entry_id),
                                   array_agg(c.subscription_id), false)
  FROM unnest(p_user, p_entry, p_sub) AS c(user_id, entry_id, subscription_id)
  JOIN user_entries ue ON ue.user_id = c.user_id AND ue.entry_id = c.entry_id
  WHERE NOT ue.read AND NOT ue.is_spam;

  UPDATE user_entries ue
  SET active_memberships = m.n
  FROM (
    SELECT p.user_id, p.entry_id, (
      SELECT count(*)::int
      FROM subscription_entries se
      JOIN subscriptions s ON s.id = se.subscription_id AND s.unsubscribed_at IS NULL
      WHERE se.user_id = p.user_id AND se.entry_id = p.entry_id
    ) AS n
    FROM (SELECT DISTINCT user_id, entry_id FROM unnest(p_user, p_entry) AS c(user_id, entry_id)) p
    WHERE EXISTS (
      SELECT 1 FROM user_entries x WHERE x.user_id = p.user_id AND x.entry_id = p.entry_id
    )
  ) m
  WHERE ue.user_id = m.user_id AND ue.entry_id = m.entry_id AND ue.active_memberships <> m.n;
END;
$$;

CREATE FUNCTION public.apply_unread_memberships(p_sign integer[], p_user uuid[], p_entry uuid[], p_sub uuid[], p_complete boolean, p_count_user uuid[] DEFAULT NULL::uuid[], p_all integer[] DEFAULT NULL::integer[], p_starred integer[] DEFAULT NULL::integer[]) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
  l_user uuid[]; l_tag uuid[]; l_n integer[];
BEGIN
  IF p_sign IS NULL AND p_count_user IS NULL THEN
    RETURN;
  END IF;

  PERFORM 1 FROM subscriptions
  WHERE id IN (SELECT unnest(p_sub))
  ORDER BY id FOR NO KEY UPDATE;

  UPDATE subscriptions s
  SET unread_count = s.unread_count + d.n
  FROM (
    SELECT subscription_id, sum(sign)::int AS n
    FROM unnest(p_sign, p_sub) AS c(sign, subscription_id)
    GROUP BY subscription_id
    HAVING sum(sign) <> 0
  ) d
  WHERE s.id = d.subscription_id;

  PERFORM 1 FROM users
  WHERE id IN (SELECT unnest(p_user) UNION SELECT unnest(p_count_user))
  ORDER BY id FOR NO KEY UPDATE;

  WITH changed AS (
    SELECT c.user_id, c.entry_id, st.tag_id, c.sign
    FROM unnest(p_sign, p_user, p_entry, p_sub) AS c(sign, user_id, entry_id, subscription_id)
    JOIN subscriptions s ON s.id = c.subscription_id AND s.unsubscribed_at IS NULL
    LEFT JOIN subscription_tags st ON st.subscription_id = s.id
    WHERE st.tag_id IS NOT NULL OR s.type <> 'saved'
  ),
  reached AS (
    SELECT user_id, entry_id, tag_id FROM changed WHERE p_complete AND sign > 0
    UNION ALL
    SELECT p.user_id, p.entry_id, st.tag_id
    FROM (SELECT DISTINCT user_id, entry_id FROM changed WHERE NOT p_complete) p
    JOIN user_entries ue ON ue.user_id = p.user_id AND ue.entry_id = p.entry_id
      AND NOT ue.read AND NOT ue.is_spam
    JOIN subscription_entries se ON se.user_id = p.user_id AND se.entry_id = p.entry_id
    JOIN subscriptions s ON s.id = se.subscription_id AND s.unsubscribed_at IS NULL
    LEFT JOIN subscription_tags st ON st.subscription_id = s.id
    WHERE st.tag_id IS NOT NULL OR s.type <> 'saved'
  ),
  per_article AS (
    SELECT user_id, tag_id, sum(now)::int AS now, sum(now - change)::int AS before
    FROM (
      SELECT user_id, entry_id, tag_id, 1 AS now, 0 AS change FROM reached
      UNION ALL
      SELECT user_id, entry_id, tag_id, 0, sign FROM changed
    ) x
    GROUP BY user_id, entry_id, tag_id
  ),
  d AS (
    SELECT user_id, tag_id, sum((now > 0)::int - (before > 0)::int)::int AS n
    FROM per_article
    GROUP BY user_id, tag_id
    HAVING sum((now > 0)::int - (before > 0)::int) <> 0
  )
  SELECT array_agg(user_id), array_agg(tag_id), array_agg(n) INTO l_user, l_tag, l_n FROM d;

  UPDATE users u
  SET uncategorized_unread_count = u.uncategorized_unread_count + d.uc,
      saved_unread_count = u.saved_unread_count + d.sv,
      all_unread_count = u.all_unread_count + d.al,
      starred_unread_count = u.starred_unread_count + d.st
  FROM (
    SELECT user_id, sum(uc)::int AS uc, sum(sv)::int AS sv, sum(al)::int AS al, sum(st)::int AS st
    FROM (
      SELECT l.user_id, l.n AS uc, 0 AS sv, 0 AS al, 0 AS st
      FROM unnest(l_user, l_tag, l_n) AS l(user_id, tag_id, n)
      WHERE l.tag_id IS NULL
      UNION ALL
      SELECT c.user_id, 0, c.sign, 0, 0
      FROM unnest(p_sign, p_user, p_sub) AS c(sign, user_id, subscription_id)
      JOIN subscriptions s ON s.id = c.subscription_id AND s.type = 'saved'
      UNION ALL
      SELECT r.user_id, 0, 0, r.al, r.st
      FROM unnest(p_count_user, p_all, p_starred) AS r(user_id, al, st)
    ) x
    GROUP BY user_id
    HAVING sum(uc) <> 0 OR sum(sv) <> 0 OR sum(al) <> 0 OR sum(st) <> 0
  ) d
  WHERE u.id = d.user_id;

  UPDATE tags t
  SET unread_count = t.unread_count + d.n
  FROM (
    SELECT l.tag_id, sum(l.n)::int AS n
    FROM unnest(l_tag, l_n) AS l(tag_id, n)
    WHERE l.tag_id IS NOT NULL
    GROUP BY l.tag_id
  ) d
  WHERE t.id = d.tag_id AND d.n <> 0;
END;
$$;

CREATE FUNCTION public.collection_entries_copy_memberships_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM subscription_entries se
  USING old_rows o
  WHERE se.subscription_id = o.subscription_id AND se.entry_id = o.entry_id;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.collection_entries_copy_memberships_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO subscription_entries (subscription_id, user_id, entry_id, published_or_fetched_at)
  SELECT n.subscription_id, n.user_id, n.entry_id, ue.published_or_fetched_at
  FROM new_rows n
  JOIN user_entries ue ON ue.user_id = n.user_id AND ue.entry_id = n.entry_id
  ON CONFLICT DO NOTHING;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.ensure_saved_subscriptions(p_users uuid[]) RETURNS integer
    LANGUAGE sql
    AS $$
  WITH created AS (
    INSERT INTO subscriptions (id, user_id, type, custom_title, greader_stream_id,
                               subscribed_at, created_at, updated_at)
    SELECT uuidv7(), f.user_id, 'saved', 'Saved', f.greader_stream_id, f.created_at, now(), now()
    FROM feeds f
    WHERE f.type = 'saved' AND f.user_id = ANY (p_users)
    ORDER BY f.user_id
    ON CONFLICT (user_id) WHERE type = 'saved' DO NOTHING
    RETURNING 1
  )
  SELECT count(*)::integer FROM created;
$$;

CREATE FUNCTION public.recompute_list_counters(p_user uuid) RETURNS void
    LANGUAGE plpgsql
    SET plan_cache_mode TO 'force_custom_plan'
    AS $$
DECLARE
  x_tag uuid[]; x_n integer[];
BEGIN
  PERFORM 1 FROM users WHERE id = p_user FOR NO KEY UPDATE;

  SELECT array_agg(tag_id), array_agg(n) INTO x_tag, x_n
  FROM (
    SELECT tag_id, sum(k - 1)::int AS n
    FROM (
      SELECT se.entry_id, st.tag_id, count(*) AS k
      FROM user_entries ue
      JOIN subscription_entries se ON se.user_id = ue.user_id AND se.entry_id = ue.entry_id
      JOIN subscriptions s ON s.id = se.subscription_id AND s.unsubscribed_at IS NULL
      LEFT JOIN subscription_tags st ON st.subscription_id = s.id
      WHERE ue.user_id = p_user AND ue.active_memberships > 1 AND NOT ue.read AND NOT ue.is_spam
        AND (st.tag_id IS NOT NULL OR s.type <> 'saved')
      GROUP BY se.entry_id, st.tag_id
    ) m
    WHERE k > 1
    GROUP BY tag_id
  ) x;

  UPDATE users u
  SET uncategorized_unread_count = f.n
  FROM (
    SELECT (
      SELECT COALESCE(sum(s.unread_count), 0)::int
      FROM subscriptions s
      WHERE s.user_id = p_user AND s.unsubscribed_at IS NULL AND s.type <> 'saved'
        AND NOT EXISTS (SELECT 1 FROM subscription_tags st WHERE st.subscription_id = s.id)
    ) - COALESCE((SELECT sum(x.n) FROM unnest(x_tag, x_n) AS x(tag_id, n) WHERE x.tag_id IS NULL), 0)::int AS n
  ) f
  WHERE u.id = p_user AND u.uncategorized_unread_count IS DISTINCT FROM f.n;

  UPDATE tags t
  SET unread_count = COALESCE(f.n, 0) - COALESCE(x.n, 0)
  FROM tags t2
  LEFT JOIN (
    SELECT st.tag_id, sum(s.unread_count)::int AS n
    FROM subscription_tags st
    JOIN subscriptions s ON s.id = st.subscription_id AND s.unsubscribed_at IS NULL
    WHERE s.user_id = p_user
    GROUP BY st.tag_id
  ) f ON f.tag_id = t2.id
  LEFT JOIN unnest(x_tag, x_n) AS x(tag_id, n) ON x.tag_id = t2.id
  WHERE t.id = t2.id AND t2.user_id = p_user
    AND t.unread_count IS DISTINCT FROM COALESCE(f.n, 0) - COALESCE(x.n, 0);
END;
$$;

CREATE FUNCTION public.subscription_entries_counters() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_mode text := current_setting('lion.memberships', true);
  v_sign integer := CASE WHEN TG_OP = 'INSERT' THEN 1 ELSE -1 END;
  v_user uuid[]; v_entry uuid[]; v_sub uuid[];
BEGIN
  IF NOT EXISTS (SELECT 1 FROM changed_rows) THEN
    RETURN NULL;
  END IF;
  IF TG_OP = 'INSERT' THEN
    PERFORM 1 FROM subscriptions
    WHERE id IN (SELECT DISTINCT subscription_id FROM changed_rows)
    ORDER BY id FOR NO KEY UPDATE;
  END IF;
  IF v_mode = 'new_rows' THEN
    UPDATE user_entries ue
    SET active_memberships = (s.unsubscribed_at IS NULL)::int
    FROM changed_rows c
    JOIN subscriptions s ON s.id = c.subscription_id
    WHERE ue.user_id = c.user_id AND ue.entry_id = c.entry_id
      AND ue.active_memberships <> (s.unsubscribed_at IS NULL)::int;
    PERFORM apply_unread_memberships(array_agg(1), array_agg(c.user_id), array_agg(c.entry_id),
                                     array_agg(c.subscription_id), true)
    FROM changed_rows c
    JOIN user_entries ue ON ue.user_id = c.user_id AND ue.entry_id = c.entry_id
    WHERE NOT ue.read AND NOT ue.is_spam;
    RETURN NULL;
  END IF;
  SELECT array_agg(user_id), array_agg(entry_id), array_agg(subscription_id)
  INTO v_user, v_entry, v_sub
  FROM changed_rows;
  PERFORM apply_membership_changes(v_sign, v_user, v_entry, v_sub);
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.subscription_tags_recompute_lists() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM recompute_list_counters(u.user_id)
  FROM (
    SELECT DISTINCT s.user_id FROM changed_rows c JOIN subscriptions s ON s.id = c.subscription_id
    ORDER BY s.user_id
  ) u;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.subscriptions_deleted_recompute_lists() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM recompute_list_counters(OLD.user_id);
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.subscriptions_empty_unsubscribed_collection() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  WITH removed AS (
    DELETE FROM collection_entries ce
    WHERE ce.subscription_id = NEW.id
    RETURNING ce.user_id, ce.entry_id
  )
  UPDATE user_entries ue
  SET updated_at = now()
  FROM removed r
  WHERE ue.user_id = r.user_id AND ue.entry_id = r.entry_id;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.subscriptions_recompute_lists() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  a_id uuid[]; a_user uuid[]; a_d integer[];
BEGIN
  SELECT array_agg(id), array_agg(user_id), array_agg(d) INTO a_id, a_user, a_d
  FROM (
    SELECT id, user_id, sum(d)::int AS d
    FROM (
      SELECT id, user_id, CASE WHEN unsubscribed_at IS NULL THEN 1 ELSE 0 END AS d FROM changed_rows
      UNION ALL
      SELECT id, user_id, CASE WHEN unsubscribed_at IS NULL THEN -1 ELSE 0 END FROM old_rows
    ) x
    GROUP BY id, user_id
    HAVING sum(d) <> 0
  ) a;
  IF a_id IS NULL THEN
    RETURN NULL;
  END IF;

  UPDATE user_entries ue
  SET active_memberships = ue.active_memberships + m.d
  FROM (
    SELECT se.user_id, se.entry_id, sum(a.d)::int AS d
    FROM unnest(a_id, a_d) AS a(id, d)
    JOIN subscription_entries se ON se.subscription_id = a.id
    GROUP BY se.user_id, se.entry_id
  ) m
  WHERE ue.user_id = m.user_id AND ue.entry_id = m.entry_id AND m.d <> 0;

  PERFORM recompute_list_counters(u.user_id)
  FROM (SELECT DISTINCT user_id FROM unnest(a_user) AS a(user_id) ORDER BY user_id) u;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_copy_membership_restamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  r_user uuid[]; r_entry uuid[]; r_sub uuid[]; r_at timestamptz[];
BEGIN
  SELECT array_agg(user_id), array_agg(entry_id), array_agg(subscription_id), array_agg(at)
  INTO r_user, r_entry, r_sub, r_at
  FROM (
    SELECT user_id, entry_id, subscription_id, max(published_or_fetched_at) AS at
    FROM (
      SELECT 1 AS sign, user_id, entry_id, subscription_id, published_or_fetched_at FROM new_rows
      UNION ALL
      SELECT -1, user_id, entry_id, subscription_id, published_or_fetched_at FROM old_rows
    ) x
    WHERE subscription_id IS NOT NULL
    GROUP BY user_id, entry_id, subscription_id
    HAVING sum(sign) > 0
  ) r;
  IF r_user IS NULL THEN
    RETURN NULL;
  END IF;
  INSERT INTO subscription_entries (subscription_id, user_id, entry_id, published_or_fetched_at)
  SELECT * FROM unnest(r_sub, r_user, r_entry, r_at)
  ON CONFLICT DO NOTHING;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_copy_memberships_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_users uuid[];
BEGIN
  PERFORM set_config('lion.memberships', 'new_rows', true);
  INSERT INTO subscription_entries (subscription_id, user_id, entry_id, published_or_fetched_at)
  SELECT subscription_id, user_id, entry_id, published_or_fetched_at
  FROM new_rows
  WHERE subscription_id IS NOT NULL
  ON CONFLICT DO NOTHING;
  PERFORM set_config('lion.memberships', '', true);

  IF NOT EXISTS (SELECT 1 FROM new_rows WHERE subscription_id IS NULL) THEN
    RETURN NULL;
  END IF;

  SELECT array_agg(DISTINCT n.user_id) INTO v_users
  FROM new_rows n
  JOIN entries e ON e.id = n.entry_id
  WHERE n.subscription_id IS NULL AND e.type = 'saved';
  IF v_users IS NULL THEN
    RETURN NULL;
  END IF;

  PERFORM ensure_saved_subscriptions(v_users);

  PERFORM set_config('lion.memberships', 'new_rows', true);
  INSERT INTO subscription_entries (subscription_id, user_id, entry_id, published_or_fetched_at)
  SELECT s.id, n.user_id, n.entry_id, n.published_or_fetched_at
  FROM new_rows n
  JOIN entries e ON e.id = n.entry_id
  JOIN subscriptions s ON s.user_id = n.user_id AND s.type = 'saved'
  WHERE n.subscription_id IS NULL AND e.type = 'saved'
  ON CONFLICT DO NOTHING;
  PERFORM set_config('lion.memberships', '', true);
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_counters_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  m_sign integer[]; m_user uuid[]; m_entry uuid[]; m_sub uuid[];
  c_user uuid[]; c_all integer[]; c_starred integer[];
BEGIN
  SELECT array_agg(-1), array_agg(se.user_id), array_agg(se.entry_id), array_agg(se.subscription_id)
  INTO m_sign, m_user, m_entry, m_sub
  FROM old_rows o
  JOIN subscription_entries se ON se.user_id = o.user_id AND se.entry_id = o.entry_id
  WHERE NOT o.read AND NOT o.is_spam;

  SELECT array_agg(user_id), array_agg(al), array_agg(st)
  INTO c_user, c_all, c_starred
  FROM (
    SELECT user_id,
           -count(*) FILTER (WHERE NOT read AND NOT is_spam AND (starred OR active_memberships > 0))::int AS al,
           -count(*) FILTER (WHERE starred AND NOT read AND NOT is_spam)::int AS st
    FROM old_rows
    GROUP BY user_id
  ) d
  WHERE al <> 0 OR st <> 0;

  PERFORM apply_unread_memberships(m_sign, m_user, m_entry, m_sub, true, c_user, c_all, c_starred);

  DELETE FROM collection_entries ce
  USING old_rows o
  WHERE ce.user_id = o.user_id AND ce.entry_id = o.entry_id;
  DELETE FROM subscription_entries se
  USING old_rows o
  WHERE se.user_id = o.user_id AND se.entry_id = o.entry_id;
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_counters_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  c_user uuid[]; c_all integer[]; c_starred integer[];
BEGIN
  SELECT array_agg(user_id), array_agg(al), array_agg(st)
  INTO c_user, c_all, c_starred
  FROM (
    SELECT user_id,
           count(*) FILTER (WHERE NOT read AND NOT is_spam AND (starred OR active_memberships > 0))::int AS al,
           count(*) FILTER (WHERE starred AND NOT read AND NOT is_spam)::int AS st
    FROM new_rows
    GROUP BY user_id
  ) d
  WHERE al <> 0 OR st <> 0;

  PERFORM apply_unread_memberships(NULL, NULL, NULL, NULL, true, c_user, c_all, c_starred);
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_counters_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  m_sign integer[]; m_user uuid[]; m_entry uuid[]; m_sub uuid[];
  c_user uuid[]; c_all integer[]; c_starred integer[];
BEGIN
  SELECT array_agg(f.n), array_agg(se.user_id), array_agg(se.entry_id), array_agg(se.subscription_id)
  INTO m_sign, m_user, m_entry, m_sub
  FROM (
    SELECT user_id, entry_id, sum(sign)::int AS n
    FROM (
      SELECT 1 AS sign, user_id, entry_id FROM new_rows WHERE NOT read AND NOT is_spam
      UNION ALL
      SELECT -1, user_id, entry_id FROM old_rows WHERE NOT read AND NOT is_spam
    ) x
    GROUP BY user_id, entry_id
    HAVING sum(sign) <> 0
  ) f
  JOIN subscription_entries se ON se.user_id = f.user_id AND se.entry_id = f.entry_id;

  SELECT array_agg(user_id), array_agg(al), array_agg(st)
  INTO c_user, c_all, c_starred
  FROM (
    SELECT user_id, sum(al)::int AS al, sum(st)::int AS st
    FROM (
      SELECT user_id,
             (NOT read AND NOT is_spam AND (starred OR active_memberships > 0))::int AS al,
             (starred AND NOT read AND NOT is_spam)::int AS st
      FROM new_rows
      UNION ALL
      SELECT user_id,
             -((NOT read AND NOT is_spam AND (starred OR active_memberships > 0))::int),
             -((starred AND NOT read AND NOT is_spam)::int)
      FROM old_rows
    ) x
    GROUP BY user_id
    HAVING sum(al) <> 0 OR sum(st) <> 0
  ) d;

  PERFORM apply_unread_memberships(m_sign, m_user, m_entry, m_sub, true, c_user, c_all, c_starred);
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.user_entries_fill_denormalized() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  v_feed_id uuid;
  v_type feed_type;
BEGIN
  IF NEW.published_or_fetched_at IS NULL
     OR NEW.is_spam IS NULL
     OR NEW.subscription_id IS NULL THEN
    SELECT COALESCE(NEW.published_or_fetched_at, e.published_at, e.fetched_at),
           COALESCE(NEW.is_spam, e.is_spam),
           e.feed_id, e.type
      INTO NEW.published_or_fetched_at, NEW.is_spam, v_feed_id, v_type
      FROM entries e
      WHERE e.id = NEW.entry_id;
    IF NEW.subscription_id IS NULL THEN
      SELECT s.id
        INTO NEW.subscription_id
        FROM subscriptions s
        WHERE s.user_id = NEW.user_id
          AND s.feed_id = v_feed_id;
    END IF;
  END IF;
  IF NEW.subscription_id IS NOT NULL THEN
    NEW.active_memberships := (
      SELECT count(*) FROM subscriptions s
      WHERE s.id = NEW.subscription_id AND s.unsubscribed_at IS NULL
    );
  ELSIF v_type = 'saved' THEN
    NEW.active_memberships := 1;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TABLE public.api_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    scopes text[] DEFAULT '{}'::text[] NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    last_used_at timestamp with time zone
);

CREATE TABLE public.blocked_senders (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    sender_email text NOT NULL,
    blocked_at timestamp with time zone DEFAULT now() NOT NULL,
    list_unsubscribe_mailto text,
    unsubscribe_sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.collection_entries (
    subscription_id uuid NOT NULL,
    user_id uuid NOT NULL,
    entry_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.discord_api_token_links (
    discord_id text NOT NULL,
    token_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.entries (
    id uuid NOT NULL,
    feed_id uuid NOT NULL,
    guid text NOT NULL,
    url text,
    title text,
    author text,
    content_original text,
    summary text,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone NOT NULL,
    content_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    content_cleaned text,
    type public.feed_type NOT NULL,
    site_name text,
    image_url text,
    spam_score real,
    is_spam boolean DEFAULT false NOT NULL,
    list_unsubscribe_mailto text,
    list_unsubscribe_https text,
    list_unsubscribe_post boolean,
    last_seen_at timestamp with time zone,
    full_content_original text,
    full_content_cleaned text,
    full_content_fetched_at timestamp with time zone,
    full_content_error text,
    full_content_hash text,
    unsubscribe_url text,
    greader_item_id bigint NOT NULL,
    is_placeholder boolean DEFAULT false NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, "left"(((COALESCE(title, ''::text) || ' '::text) || COALESCE(NULLIF(content_cleaned, ''::text), content_original, ''::text)), 300000))) STORED,
    is_backfill boolean DEFAULT false NOT NULL,
    CONSTRAINT entries_last_seen_only_fetched CHECK (((type = 'web'::public.feed_type) = (last_seen_at IS NOT NULL))),
    CONSTRAINT entries_saved_metadata_only_saved CHECK (((type = 'saved'::public.feed_type) OR ((site_name IS NULL) AND (image_url IS NULL)))),
    CONSTRAINT entries_spam_only_email CHECK (((type = 'email'::public.feed_type) OR ((spam_score IS NULL) AND (is_spam = false)))),
    CONSTRAINT entries_unsubscribe_only_email CHECK (((type = 'email'::public.feed_type) OR ((list_unsubscribe_mailto IS NULL) AND (list_unsubscribe_https IS NULL) AND (list_unsubscribe_post IS NULL))))
);
ALTER TABLE ONLY public.entries ALTER COLUMN content_original SET COMPRESSION lz4;
ALTER TABLE ONLY public.entries ALTER COLUMN summary SET COMPRESSION lz4;
ALTER TABLE ONLY public.entries ALTER COLUMN content_cleaned SET COMPRESSION lz4;
ALTER TABLE ONLY public.entries ALTER COLUMN full_content_original SET COMPRESSION lz4;
ALTER TABLE ONLY public.entries ALTER COLUMN full_content_cleaned SET COMPRESSION lz4;

CREATE SEQUENCE public.entries_greader_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.entries_greader_item_id_seq OWNED BY public.entries.greader_item_id;

CREATE TABLE public.entry_summaries (
    id uuid NOT NULL,
    content_hash text NOT NULL,
    summary_text text,
    model_id text,
    prompt_version smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    generated_at timestamp with time zone,
    error text,
    error_at timestamp with time zone,
    user_id uuid,
    max_words integer,
    prompt_hash text
);
ALTER TABLE ONLY public.entry_summaries ALTER COLUMN summary_text SET COMPRESSION lz4;

CREATE TABLE public.entry_tombstones (
    user_id uuid NOT NULL,
    entry_id uuid NOT NULL,
    deleted_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE public.greader_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.feeds (
    id uuid NOT NULL,
    type public.feed_type NOT NULL,
    url text,
    title text,
    description text,
    site_url text,
    etag text,
    last_modified_header text,
    last_fetched_at timestamp with time zone,
    next_fetch_at timestamp with time zone,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    hub_url text,
    self_url text,
    websub_active boolean DEFAULT false NOT NULL,
    user_id uuid,
    email_sender_pattern text,
    body_hash text,
    last_entries_updated_at timestamp with time zone,
    redirect_url text,
    redirect_first_seen_at timestamp with time zone,
    last_fetch_entry_count integer,
    last_fetch_size_bytes integer,
    greader_stream_id bigint DEFAULT nextval('public.greader_id_seq'::regclass) NOT NULL,
    ttl_minutes integer,
    syndication_update_period text,
    syndication_update_frequency integer,
    CONSTRAINT feed_type_user_id CHECK (((type = ANY (ARRAY['email'::public.feed_type, 'saved'::public.feed_type])) = (user_id IS NOT NULL))),
    CONSTRAINT feeds_type_not_collection CHECK ((type <> 'collection'::public.feed_type))
);

CREATE TABLE public.ingest_addresses (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token public.citext NOT NULL,
    label text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone
);

CREATE TABLE public.invites (
    id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    used_by_user_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.jobs (
    id uuid NOT NULL,
    type text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    next_run_at timestamp with time zone,
    running_since timestamp with time zone,
    last_run_at timestamp with time zone,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.narration_content (
    id uuid NOT NULL,
    content_hash text NOT NULL,
    content_narration text,
    generated_at timestamp with time zone,
    error text,
    error_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    paragraph_map jsonb
);
ALTER TABLE ONLY public.narration_content ALTER COLUMN content_narration SET COMPRESSION lz4;

CREATE TABLE public.oauth_access_tokens (
    id uuid NOT NULL,
    token_hash text NOT NULL,
    client_id text NOT NULL,
    user_id uuid NOT NULL,
    scopes text[] NOT NULL,
    resource text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_used_at timestamp with time zone
);

CREATE TABLE public.oauth_accounts (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_account_id text NOT NULL,
    access_token text,
    refresh_token text,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    scopes text[]
);

CREATE TABLE public.oauth_authorization_codes (
    id uuid NOT NULL,
    code_hash text NOT NULL,
    client_id text NOT NULL,
    user_id uuid NOT NULL,
    redirect_uri text NOT NULL,
    scopes text[] NOT NULL,
    code_challenge text NOT NULL,
    code_challenge_method text DEFAULT 'S256'::text NOT NULL,
    resource text,
    state text,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT oauth_auth_codes_pkce_s256 CHECK ((code_challenge_method = 'S256'::text))
);

CREATE TABLE public.oauth_clients (
    id uuid NOT NULL,
    client_id text NOT NULL,
    client_secret_hash text,
    name text NOT NULL,
    redirect_uris text[] NOT NULL,
    grant_types text[] DEFAULT '{authorization_code,refresh_token}'::text[] NOT NULL,
    scopes text[],
    is_public boolean DEFAULT true NOT NULL,
    metadata_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.oauth_consent_grants (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    client_id text NOT NULL,
    scopes text[] NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone
);

CREATE TABLE public.oauth_refresh_tokens (
    id uuid NOT NULL,
    token_hash text NOT NULL,
    client_id text NOT NULL,
    user_id uuid NOT NULL,
    scopes text[] NOT NULL,
    access_token_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by_id uuid,
    resource text
);

CREATE TABLE public.opml_imports (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    total_feeds integer NOT NULL,
    imported_count integer DEFAULT 0 NOT NULL,
    skipped_count integer DEFAULT 0 NOT NULL,
    failed_count integer DEFAULT 0 NOT NULL,
    feeds_data jsonb NOT NULL,
    results jsonb DEFAULT '[]'::jsonb NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);

CREATE TABLE public.sessions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_active_at timestamp with time zone DEFAULT now() NOT NULL,
    scopes text[]
);

CREATE TABLE public.subscription_entries (
    subscription_id uuid NOT NULL,
    user_id uuid NOT NULL,
    entry_id uuid NOT NULL,
    published_or_fetched_at timestamp with time zone NOT NULL
);

CREATE TABLE public.subscription_tags (
    subscription_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.subscriptions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    feed_id uuid,
    custom_title text,
    subscribed_at timestamp with time zone DEFAULT now() NOT NULL,
    unsubscribed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    fetch_full_content boolean DEFAULT false NOT NULL,
    unread_count integer DEFAULT 0 NOT NULL,
    starred_unread_count integer DEFAULT 0 NOT NULL,
    greader_stream_id bigint DEFAULT nextval('public.greader_id_seq'::regclass) NOT NULL,
    type public.feed_type NOT NULL,
    CONSTRAINT subscriptions_collection_feedless CHECK (((type <> 'collection'::public.feed_type) OR (feed_id IS NULL))),
    CONSTRAINT subscriptions_collection_named CHECK (((type <> 'collection'::public.feed_type) OR (custom_title IS NOT NULL))),
    CONSTRAINT subscriptions_saved_feedless CHECK (((type <> 'saved'::public.feed_type) OR (feed_id IS NULL)))
);

CREATE TABLE public.tags (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    color text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    greader_sortid bigint DEFAULT nextval('public.greader_id_seq'::regclass) NOT NULL,
    unread_count integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.user_api_keys (
    user_id uuid NOT NULL,
    provider text NOT NULL,
    encrypted_key text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.user_entries (
    user_id uuid CONSTRAINT user_entry_states_user_id_not_null NOT NULL,
    entry_id uuid CONSTRAINT user_entry_states_entry_id_not_null NOT NULL,
    read boolean DEFAULT false CONSTRAINT user_entry_states_read_not_null NOT NULL,
    starred boolean DEFAULT false CONSTRAINT user_entry_states_starred_not_null NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    read_changed_at timestamp with time zone,
    starred_changed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    published_or_fetched_at timestamp with time zone NOT NULL,
    subscription_id uuid,
    is_spam boolean NOT NULL,
    active_memberships integer DEFAULT 0 NOT NULL,
    CONSTRAINT user_entries_active_memberships_nonnegative CHECK ((active_memberships >= 0))
);

CREATE VIEW public.user_feeds AS
 SELECT s.id,
    s.user_id,
    s.subscribed_at,
    s.created_at,
    s.feed_id,
    s.custom_title,
    s.fetch_full_content,
    s.type,
    COALESCE(s.custom_title, f.title) AS title,
    COALESCE(f.title, s.custom_title) AS original_title,
    f.url,
    f.site_url,
    f.description,
    s.unread_count,
    s.greader_stream_id
   FROM (public.subscriptions s
     LEFT JOIN public.feeds f ON ((f.id = s.feed_id)))
  WHERE (s.unsubscribed_at IS NULL);

CREATE TABLE public.users (
    id uuid NOT NULL,
    email public.citext NOT NULL,
    email_verified_at timestamp with time zone,
    password_hash text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    invite_id uuid,
    show_spam boolean DEFAULT false NOT NULL,
    summarization_model text,
    summarization_max_words integer,
    summarization_prompt text,
    tos_agreed_at timestamp with time zone,
    privacy_policy_agreed_at timestamp with time zone,
    not_eu_agreed_at timestamp with time zone,
    last_active_at timestamp with time zone,
    saved_unread_count integer DEFAULT 0 NOT NULL,
    starred_unread_count integer DEFAULT 0 NOT NULL,
    greader_user_id bigint DEFAULT nextval('public.greader_id_seq'::regclass) NOT NULL,
    narration_model text,
    getting_started_at timestamp with time zone,
    uncategorized_unread_count integer DEFAULT 0 NOT NULL,
    all_unread_count integer DEFAULT 0 NOT NULL
);

CREATE VIEW public.visible_entries AS
 SELECT ue.user_id,
    e.id,
    e.feed_id,
    e.type,
    e.guid,
    e.url,
    e.title,
    e.author,
    e.content_original,
    e.content_cleaned,
    e.summary,
    e.site_name,
    e.image_url,
    e.published_at,
    e.fetched_at,
    e.last_seen_at,
    e.content_hash,
    e.full_content_hash,
    e.spam_score,
    e.is_spam,
    e.list_unsubscribe_mailto,
    e.list_unsubscribe_https,
    e.list_unsubscribe_post,
    e.created_at,
    GREATEST(e.updated_at, ue.updated_at) AS updated_at,
    e.full_content_original,
    e.full_content_cleaned,
    e.full_content_fetched_at,
    e.full_content_error,
    ue.read,
    ue.starred,
    s.id AS subscription_id,
    e.unsubscribe_url,
    ue.read_changed_at,
    ue.published_or_fetched_at,
    e.greader_item_id,
    s.greader_stream_id AS subscription_greader_stream_id,
    e.search_vector
   FROM ((public.user_entries ue
     JOIN public.entries e ON ((e.id = ue.entry_id)))
     LEFT JOIN public.subscriptions s ON ((s.id = ue.subscription_id)))
  WHERE (ue.starred OR (ue.active_memberships > 0));

CREATE TABLE public.websub_hub_stats (
    hub_url text NOT NULL,
    articles_announced_by_hub bigint DEFAULT 0 NOT NULL,
    articles_announced_by_backup bigint DEFAULT 0 NOT NULL,
    articles_near_miss bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.websub_subscriptions (
    id uuid NOT NULL,
    feed_id uuid NOT NULL,
    hub_url text NOT NULL,
    topic_url text NOT NULL,
    callback_secret text NOT NULL,
    state public.websub_state DEFAULT 'pending'::public.websub_state NOT NULL,
    lease_seconds integer,
    expires_at timestamp with time zone,
    last_challenge_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    unsubscribe_requested_at timestamp with time zone
);

ALTER TABLE ONLY public.entries ALTER COLUMN greader_item_id SET DEFAULT nextval('public.entries_greader_item_id_seq'::regclass);

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY public.blocked_senders
    ADD CONSTRAINT blocked_senders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.collection_entries
    ADD CONSTRAINT collection_entries_pkey PRIMARY KEY (subscription_id, entry_id);

ALTER TABLE ONLY public.discord_api_token_links
    ADD CONSTRAINT discord_api_token_links_pkey PRIMARY KEY (discord_id);

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_pkey PRIMARY KEY (id);

ALTER TABLE public.entries
    ADD CONSTRAINT entries_type_not_collection CHECK ((type <> 'collection'::public.feed_type)) NOT VALID;

ALTER TABLE ONLY public.entry_summaries
    ADD CONSTRAINT entry_summaries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.entry_summaries
    ADD CONSTRAINT entry_summaries_user_content_unique UNIQUE (user_id, content_hash);

ALTER TABLE ONLY public.entry_tombstones
    ADD CONSTRAINT entry_tombstones_pkey PRIMARY KEY (user_id, entry_id);

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_url_unique UNIQUE (url);

ALTER TABLE ONLY public.ingest_addresses
    ADD CONSTRAINT ingest_addresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ingest_addresses
    ADD CONSTRAINT ingest_addresses_token_unique UNIQUE (token);

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_token_unique UNIQUE (token);

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.narration_content
    ADD CONSTRAINT narration_content_content_hash_unique UNIQUE (content_hash);

ALTER TABLE ONLY public.narration_content
    ADD CONSTRAINT narration_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_authorization_codes
    ADD CONSTRAINT oauth_authorization_codes_code_hash_key UNIQUE (code_hash);

ALTER TABLE ONLY public.oauth_authorization_codes
    ADD CONSTRAINT oauth_authorization_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_client_id_key UNIQUE (client_id);

ALTER TABLE ONLY public.oauth_clients
    ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_consent_grants
    ADD CONSTRAINT oauth_consent_grants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_consent_grants
    ADD CONSTRAINT oauth_consent_grants_user_id_client_id_key UNIQUE (user_id, client_id);

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY public.opml_imports
    ADD CONSTRAINT opml_imports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash);

ALTER TABLE ONLY public.subscription_entries
    ADD CONSTRAINT subscription_entries_pkey PRIMARY KEY (subscription_id, entry_id);

ALTER TABLE ONLY public.subscription_tags
    ADD CONSTRAINT subscription_tags_subscription_id_tag_id_pk PRIMARY KEY (subscription_id, tag_id);

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.blocked_senders
    ADD CONSTRAINT uq_blocked_senders_user_email UNIQUE (user_id, sender_email);

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT uq_entries_feed_guid UNIQUE (feed_id, guid);

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT uq_feeds_email_user_sender UNIQUE (user_id, email_sender_pattern);

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT uq_oauth_accounts_provider_account UNIQUE (provider, provider_account_id);

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT uq_subscriptions_user_feed UNIQUE (user_id, feed_id);

ALTER TABLE ONLY public.websub_subscriptions
    ADD CONSTRAINT uq_websub_subscriptions_feed_hub UNIQUE (feed_id, hub_url);

ALTER TABLE ONLY public.user_api_keys
    ADD CONSTRAINT user_api_keys_pkey PRIMARY KEY (user_id, provider);

ALTER TABLE ONLY public.user_entries
    ADD CONSTRAINT user_entry_states_user_id_entry_id_pk PRIMARY KEY (user_id, entry_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.websub_hub_stats
    ADD CONSTRAINT websub_hub_stats_pkey PRIMARY KEY (hub_url);

ALTER TABLE ONLY public.websub_subscriptions
    ADD CONSTRAINT websub_subscriptions_pkey PRIMARY KEY (id);

CREATE INDEX idx_api_tokens_user ON public.api_tokens USING btree (user_id);

CREATE INDEX idx_blocked_senders_user ON public.blocked_senders USING btree (user_id);

CREATE INDEX idx_collection_entries_user_entry ON public.collection_entries USING btree (user_id, entry_id);

CREATE INDEX idx_discord_api_token_links_token ON public.discord_api_token_links USING btree (token_id);

CREATE INDEX idx_entries_feed ON public.entries USING btree (feed_id, id);

CREATE INDEX idx_entries_feed_published_coalesce ON public.entries USING btree (feed_id, COALESCE(published_at, fetched_at) DESC, id DESC);

CREATE INDEX idx_entries_feed_updated_at ON public.entries USING btree (feed_id, updated_at);

CREATE INDEX idx_entries_fetched ON public.entries USING btree (feed_id, fetched_at);

CREATE UNIQUE INDEX idx_entries_greader_item_id ON public.entries USING btree (greader_item_id);

CREATE INDEX idx_entries_last_seen ON public.entries USING btree (feed_id, last_seen_at) WHERE (type = 'web'::public.feed_type);

CREATE INDEX idx_entries_published_coalesce ON public.entries USING btree (COALESCE(published_at, fetched_at) DESC, id DESC);

CREATE INDEX idx_entries_search_vector ON public.entries USING gin (search_vector);

CREATE INDEX idx_entries_spam ON public.entries USING btree (feed_id, is_spam);

CREATE INDEX idx_entries_type ON public.entries USING btree (type);

CREATE INDEX idx_entries_web_guid_canonical ON public.entries USING btree (regexp_replace(guid, '^https?://'::text, 'https://'::text)) WHERE (type = 'web'::public.feed_type);

CREATE INDEX idx_entry_summaries_prompt_version ON public.entry_summaries USING btree (prompt_version) WHERE (summary_text IS NOT NULL);

CREATE INDEX idx_entry_tombstones_deleted_at ON public.entry_tombstones USING btree (deleted_at);

CREATE INDEX idx_entry_tombstones_user_deleted_at ON public.entry_tombstones USING btree (user_id, deleted_at);

CREATE UNIQUE INDEX idx_feeds_greader_stream_id ON public.feeds USING btree (greader_stream_id);

CREATE INDEX idx_feeds_next_fetch ON public.feeds USING btree (next_fetch_at);

CREATE INDEX idx_feeds_type ON public.feeds USING btree (type);

CREATE INDEX idx_feeds_user_id ON public.feeds USING btree (user_id);

CREATE INDEX idx_ingest_addresses_user ON public.ingest_addresses USING btree (user_id);

CREATE INDEX idx_invites_expires ON public.invites USING btree (expires_at);

CREATE UNIQUE INDEX idx_jobs_feed_id ON public.jobs USING btree (((payload ->> 'feedId'::text))) WHERE (type = 'fetch_feed'::text);

CREATE UNIQUE INDEX idx_jobs_full_content_pending_feed_id ON public.jobs USING btree (((payload ->> 'feedId'::text))) WHERE ((type = 'fetch_full_content'::text) AND ((payload ->> 'pending'::text) = 'true'::text) AND (running_since IS NULL) AND (last_run_at IS NULL));

CREATE INDEX idx_jobs_polling ON public.jobs USING btree (type, next_run_at);

CREATE INDEX idx_oauth_access_tokens_client ON public.oauth_access_tokens USING btree (client_id);

CREATE INDEX idx_oauth_access_tokens_expires ON public.oauth_access_tokens USING btree (expires_at);

CREATE INDEX idx_oauth_access_tokens_user ON public.oauth_access_tokens USING btree (user_id);

CREATE INDEX idx_oauth_accounts_scopes ON public.oauth_accounts USING gin (scopes);

CREATE INDEX idx_oauth_accounts_user ON public.oauth_accounts USING btree (user_id);

CREATE INDEX idx_oauth_auth_codes_expires ON public.oauth_authorization_codes USING btree (expires_at);

CREATE INDEX idx_oauth_auth_codes_user ON public.oauth_authorization_codes USING btree (user_id);

CREATE INDEX idx_oauth_consent_grants_client ON public.oauth_consent_grants USING btree (client_id);

CREATE INDEX idx_oauth_refresh_tokens_access ON public.oauth_refresh_tokens USING btree (access_token_id);

CREATE INDEX idx_oauth_refresh_tokens_client ON public.oauth_refresh_tokens USING btree (client_id);

CREATE INDEX idx_oauth_refresh_tokens_expires ON public.oauth_refresh_tokens USING btree (expires_at);

CREATE INDEX idx_oauth_refresh_tokens_user ON public.oauth_refresh_tokens USING btree (user_id);

CREATE INDEX idx_opml_imports_status ON public.opml_imports USING btree (status);

CREATE INDEX idx_opml_imports_user ON public.opml_imports USING btree (user_id);

CREATE INDEX idx_sessions_last_active ON public.sessions USING btree (last_active_at);

CREATE INDEX idx_sessions_user ON public.sessions USING btree (user_id);

CREATE INDEX idx_subscription_entries_timeline ON public.subscription_entries USING btree (subscription_id, published_or_fetched_at DESC, entry_id DESC);

CREATE INDEX idx_subscription_entries_user_entry ON public.subscription_entries USING btree (user_id, entry_id);

CREATE INDEX idx_subscription_tags_tag ON public.subscription_tags USING btree (tag_id);

CREATE INDEX idx_subscriptions_feed ON public.subscriptions USING btree (feed_id);

CREATE INDEX idx_subscriptions_feed_active ON public.subscriptions USING btree (feed_id) WHERE (unsubscribed_at IS NULL);

CREATE UNIQUE INDEX idx_subscriptions_greader_stream_id ON public.subscriptions USING btree (greader_stream_id);

CREATE INDEX idx_subscriptions_user_active ON public.subscriptions USING btree (user_id) WHERE (unsubscribed_at IS NULL);

CREATE INDEX idx_tags_updated_at ON public.tags USING btree (user_id, updated_at);

CREATE INDEX idx_user_entries_entry_id ON public.user_entries USING btree (entry_id);

CREATE INDEX idx_user_entries_multi_member ON public.user_entries USING btree (user_id) WHERE (active_memberships > 1);

CREATE INDEX idx_user_entries_published_or_fetched ON public.user_entries USING btree (user_id, published_or_fetched_at DESC, entry_id DESC);

CREATE INDEX idx_user_entries_read_changed_at ON public.user_entries USING btree (user_id, read_changed_at DESC, entry_id DESC);

CREATE INDEX idx_user_entries_starred ON public.user_entries USING btree (user_id) WHERE (starred = true);

CREATE INDEX idx_user_entries_subscription_timeline ON public.user_entries USING btree (subscription_id, published_or_fetched_at DESC, entry_id DESC) WHERE (subscription_id IS NOT NULL);

CREATE INDEX idx_user_entries_unread ON public.user_entries USING btree (user_id) WHERE (read = false);

CREATE INDEX idx_user_entries_updated_at ON public.user_entries USING btree (user_id, updated_at);

CREATE INDEX idx_users_getting_started_pending ON public.users USING btree (id) WHERE (getting_started_at IS NULL);

CREATE INDEX idx_users_last_active_at ON public.users USING btree (last_active_at DESC NULLS LAST, id DESC);

CREATE INDEX idx_websub_expiring ON public.websub_subscriptions USING btree (expires_at);

CREATE UNIQUE INDEX jobs_singleton_type_unique ON public.jobs USING btree (type) WHERE (type = ANY (ARRAY['renew_websub'::text, 'monitor_feed_health'::text, 'cleanup'::text, 'reconcile_counters'::text, 'reconcile_membership_counters'::text, 'backfill_getting_started'::text]));

CREATE UNIQUE INDEX uq_entries_feed_guid_canonical ON public.entries USING btree (feed_id, regexp_replace(guid, '^https?://'::text, 'https://'::text)) WHERE (type = 'web'::public.feed_type);

CREATE UNIQUE INDEX uq_feeds_saved_user ON public.feeds USING btree (user_id) WHERE (type = 'saved'::public.feed_type);

CREATE UNIQUE INDEX uq_subscriptions_id_user ON public.subscriptions USING btree (id, user_id);

CREATE UNIQUE INDEX uq_subscriptions_saved_user ON public.subscriptions USING btree (user_id) WHERE (type = 'saved'::public.feed_type);

CREATE UNIQUE INDEX uq_subscriptions_user_collection_name ON public.subscriptions USING btree (user_id, lower(custom_title)) WHERE ((type = 'collection'::public.feed_type) AND (unsubscribed_at IS NULL));

CREATE UNIQUE INDEX uq_tags_user_lower_name ON public.tags USING btree (user_id, lower(name)) WHERE (deleted_at IS NULL);

CREATE STATISTICS public.entries_guid_canonical_stats ON regexp_replace(guid, '^https?://'::text, 'https://'::text) FROM public.entries;

CREATE TRIGGER collection_entries_copy_memberships_delete_trigger AFTER DELETE ON public.collection_entries REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.collection_entries_copy_memberships_delete();

CREATE TRIGGER collection_entries_copy_memberships_insert_trigger AFTER INSERT ON public.collection_entries REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.collection_entries_copy_memberships_insert();

CREATE TRIGGER subscription_entries_counters_delete_trigger AFTER DELETE ON public.subscription_entries REFERENCING OLD TABLE AS changed_rows FOR EACH STATEMENT EXECUTE FUNCTION public.subscription_entries_counters();

CREATE TRIGGER subscription_entries_counters_insert_trigger AFTER INSERT ON public.subscription_entries REFERENCING NEW TABLE AS changed_rows FOR EACH STATEMENT EXECUTE FUNCTION public.subscription_entries_counters();

CREATE TRIGGER subscription_tags_recompute_lists_delete_trigger AFTER DELETE ON public.subscription_tags REFERENCING OLD TABLE AS changed_rows FOR EACH STATEMENT EXECUTE FUNCTION public.subscription_tags_recompute_lists();

CREATE TRIGGER subscription_tags_recompute_lists_insert_trigger AFTER INSERT ON public.subscription_tags REFERENCING NEW TABLE AS changed_rows FOR EACH STATEMENT EXECUTE FUNCTION public.subscription_tags_recompute_lists();

CREATE TRIGGER subscriptions_empty_unsubscribed_collection_trigger AFTER UPDATE OF unsubscribed_at ON public.subscriptions FOR EACH ROW WHEN (((old.unsubscribed_at IS NULL) AND (new.unsubscribed_at IS NOT NULL))) EXECUTE FUNCTION public.subscriptions_empty_unsubscribed_collection();

CREATE CONSTRAINT TRIGGER subscriptions_recompute_lists_delete_trigger AFTER DELETE ON public.subscriptions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.subscriptions_deleted_recompute_lists();

CREATE TRIGGER subscriptions_recompute_lists_update_trigger AFTER UPDATE ON public.subscriptions REFERENCING OLD TABLE AS old_rows NEW TABLE AS changed_rows FOR EACH STATEMENT EXECUTE FUNCTION public.subscriptions_recompute_lists();

CREATE TRIGGER user_entries_copy_membership_restamp_trigger AFTER UPDATE ON public.user_entries REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.user_entries_copy_membership_restamp();

CREATE TRIGGER user_entries_copy_memberships_insert_trigger AFTER INSERT ON public.user_entries REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.user_entries_copy_memberships_insert();

CREATE TRIGGER user_entries_counters_delete_trigger AFTER DELETE ON public.user_entries REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.user_entries_counters_delete();

CREATE TRIGGER user_entries_counters_insert_trigger AFTER INSERT ON public.user_entries REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.user_entries_counters_insert();

CREATE TRIGGER user_entries_counters_update_trigger AFTER UPDATE ON public.user_entries REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.user_entries_counters_update();

CREATE TRIGGER user_entries_fill_denormalized_trigger BEFORE INSERT ON public.user_entries FOR EACH ROW EXECUTE FUNCTION public.user_entries_fill_denormalized();

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.blocked_senders
    ADD CONSTRAINT blocked_senders_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collection_entries
    ADD CONSTRAINT collection_entries_subscription_id_user_id_fkey FOREIGN KEY (subscription_id, user_id) REFERENCES public.subscriptions(id, user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.collection_entries
    ADD CONSTRAINT collection_entries_user_id_entry_id_fkey FOREIGN KEY (user_id, entry_id) REFERENCES public.user_entries(user_id, entry_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.collection_entries
    ADD CONSTRAINT collection_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.discord_api_token_links
    ADD CONSTRAINT discord_api_token_links_token_id_fkey FOREIGN KEY (token_id) REFERENCES public.api_tokens(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_feed_id_feeds_id_fk FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.entry_summaries
    ADD CONSTRAINT entry_summaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.entry_tombstones
    ADD CONSTRAINT entry_tombstones_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.feeds
    ADD CONSTRAINT feeds_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ingest_addresses
    ADD CONSTRAINT ingest_addresses_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.invites
    ADD CONSTRAINT invites_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.oauth_access_tokens
    ADD CONSTRAINT oauth_access_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_accounts
    ADD CONSTRAINT oauth_accounts_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_authorization_codes
    ADD CONSTRAINT oauth_authorization_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_consent_grants
    ADD CONSTRAINT oauth_consent_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_access_token_id_fkey FOREIGN KEY (access_token_id) REFERENCES public.oauth_access_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_replaced_by_id_fkey FOREIGN KEY (replaced_by_id) REFERENCES public.oauth_refresh_tokens(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.oauth_refresh_tokens
    ADD CONSTRAINT oauth_refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.opml_imports
    ADD CONSTRAINT opml_imports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subscription_entries
    ADD CONSTRAINT subscription_entries_subscription_id_user_id_fkey FOREIGN KEY (subscription_id, user_id) REFERENCES public.subscriptions(id, user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subscription_entries
    ADD CONSTRAINT subscription_entries_user_id_entry_id_fkey FOREIGN KEY (user_id, entry_id) REFERENCES public.user_entries(user_id, entry_id) ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.subscription_tags
    ADD CONSTRAINT subscription_tags_subscription_id_subscriptions_id_fk FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subscription_tags
    ADD CONSTRAINT subscription_tags_tag_id_tags_id_fk FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_feed_id_feeds_id_fk FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_api_keys
    ADD CONSTRAINT user_api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_entries
    ADD CONSTRAINT user_entries_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.user_entries
    ADD CONSTRAINT user_entry_states_entry_id_entries_id_fk FOREIGN KEY (entry_id) REFERENCES public.entries(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_entries
    ADD CONSTRAINT user_entry_states_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_invite_id_invites_id_fk FOREIGN KEY (invite_id) REFERENCES public.invites(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.websub_subscriptions
    ADD CONSTRAINT websub_subscriptions_feed_id_feeds_id_fk FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON DELETE CASCADE;
