{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-sse/3.0.2/ktor-sse-3.0.2.module",
    "group": "io.ktor",
    "module": "ktor-sse",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-jvm-3.0.2.jar",
          "url": "ktor-sse-jvm-3.0.2.jar",
          "size": 4119,
          "sha512": "17319325c734ffae73dedaadfd17f13e30c296f4a3c924d179b0f52bbf03a3d6e56fd30370700459d32e291d83a918bd83224ca9f76eb4edd8f33a6a13c45ec3",
          "sha256": "5cfd1a6e2f68f78ae2dd00631ecd6459ecda5006b8497be9746dbb8cf34fd339",
          "sha1": "4c0f9fdc6c37501d54a6d381d4fcde1b18b3256e",
          "md5": "e26cbfed70637b358621b61b7aee8d84"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-sse-jvm-3.0.2.jar",
          "url": "ktor-sse-jvm-3.0.2.jar",
          "size": 4119,
          "sha512": "17319325c734ffae73dedaadfd17f13e30c296f4a3c924d179b0f52bbf03a3d6e56fd30370700459d32e291d83a918bd83224ca9f76eb4edd8f33a6a13c45ec3",
          "sha256": "5cfd1a6e2f68f78ae2dd00631ecd6459ecda5006b8497be9746dbb8cf34fd339",
          "sha1": "4c0f9fdc6c37501d54a6d381d4fcde1b18b3256e",
          "md5": "e26cbfed70637b358621b61b7aee8d84"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-sse-jvm-3.0.2-sources.jar",
          "url": "ktor-sse-jvm-3.0.2-sources.jar",
          "size": 1496,
          "sha512": "48632042e86418305d19cd838fe93878200efc94345ac3fab94e68f7d04999facd12cdc78a19da7f85913dd51a40750cb5d955454b2487c3d745364c108ac3a9",
          "sha256": "45887da7e131df98dbd4f3ce2dee4a8d38e4bd285c46490a515bba5cb2060ec3",
          "sha1": "5c1a75510c645446d33f7937c3a046b3f98f53f9",
          "md5": "81ad5c95a19a2490f99e3a45f7a3fd3d"
        }
      ]
    }
  ]
}
