{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sentry-compose/8.0.0/sentry-compose-8.0.0.module",
    "group": "io.sentry",
    "module": "sentry-compose",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-navigation",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-compose-release.aar",
          "url": "sentry-compose-android-8.0.0.aar",
          "size": 32754,
          "sha512": "d8072c149e8ceaea6e6321578ce1915ea0473cbeed0810e83de1e6fe31210e2e8b292eca2f76005a3af7704cfd72f4799ad5d8df91f179d87b8c0c230aa74561",
          "sha256": "fd6aaabc71a948f35caaa97e4e265437a578ea604ab0e887fc5ec64942f24940",
          "sha1": "8774016d42c1de142448d02e6b0d0399f2942427",
          "md5": "18082193c80143508c21ef149fb0b5d3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-navigation",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sentry-compose-release.aar",
          "url": "sentry-compose-android-8.0.0.aar",
          "size": 32754,
          "sha512": "d8072c149e8ceaea6e6321578ce1915ea0473cbeed0810e83de1e6fe31210e2e8b292eca2f76005a3af7704cfd72f4799ad5d8df91f179d87b8c0c230aa74561",
          "sha256": "fd6aaabc71a948f35caaa97e4e265437a578ea604ab0e887fc5ec64942f24940",
          "sha1": "8774016d42c1de142448d02e6b0d0399f2942427",
          "md5": "18082193c80143508c21ef149fb0b5d3"
        }
      ]
    }
  ]
}
