{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-io/1.7.3/kotlinx-serialization-json-io-1.7.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-io",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-io-jvm-1.7.3.jar",
          "url": "kotlinx-serialization-json-io-jvm-1.7.3.jar",
          "size": 6928,
          "sha512": "0cd61f6a2968644e6bb0bff279f100dd753fa86bd6f104c53ceb78a84c1493568dbaaf6932c517e8beab4ca68de4a9da8a79a3eec715fcfd9f9811e984db6ddb",
          "sha256": "963372b471616c2cd421fdea8085c4afb801a9aa71e5ef3acd1ba66e3450216c",
          "sha1": "8ac426493b27614559bcc2572fa007b84a814a54",
          "md5": "39e81205abb2f3513f6b655144d5503d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-io-jvm-1.7.3.jar",
          "url": "kotlinx-serialization-json-io-jvm-1.7.3.jar",
          "size": 6928,
          "sha512": "0cd61f6a2968644e6bb0bff279f100dd753fa86bd6f104c53ceb78a84c1493568dbaaf6932c517e8beab4ca68de4a9da8a79a3eec715fcfd9f9811e984db6ddb",
          "sha256": "963372b471616c2cd421fdea8085c4afb801a9aa71e5ef3acd1ba66e3450216c",
          "sha1": "8ac426493b27614559bcc2572fa007b84a814a54",
          "md5": "39e81205abb2f3513f6b655144d5503d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-io-jvm-1.7.3-sources.jar",
          "url": "kotlinx-serialization-json-io-jvm-1.7.3-sources.jar",
          "size": 3345,
          "sha512": "6b72dd4304fe93ba93651e3005ac7528dcdd5581f8d94813fdb209b42bbd4d8bc4b2a16f18a0f091eec6e4393232ab0751986f8bbf8b2b38db72545f029821fb",
          "sha256": "60a176e88a074452f03e7f359f33bed4ca734e24e008c50677468fd253af9e98",
          "sha1": "4911bd5f49bdb2b89215ac456b197d8b7a65a7d0",
          "md5": "3b4048e84fcbdfed73146d6c776b3bf8"
        }
      ]
    }
  ]
}
