title: Lion Reader Announcements
description: Service announcements and feature updates for Lion Reader
url: "https://announcements.lionreader.com"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  changelog:
    output: true
    permalink: /changelog/:year/:month/:day/:title/

feed:
  path: feed.xml
  collections:
    changelog:
      path: changelog.xml

permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
