{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage",
    "version": "31.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.7.3.jar",
          "url": "android-test-plugin-host-coverage-31.7.3.jar",
          "size": 17273,
          "sha512": "25edf9c9428572e0cdb74014c734b16759d54b49a27c11cdeb08e7c2ef4a2c2db225732222706af3c69ebd152ee08d74fc3cd586731ada909e7e8ee7dde2e4ec",
          "sha256": "a8fe3c4bb51374feee9b0f4d6f3009ed60dafa669c7308da6b18633b22129855",
          "sha1": "e3cba774eee7b2d5ef9a56b0d0db01c67ea36829",
          "md5": "109e12dfcd584373d2adc0df333b054c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.7.3.jar",
          "url": "android-test-plugin-host-coverage-31.7.3.jar",
          "size": 17273,
          "sha512": "25edf9c9428572e0cdb74014c734b16759d54b49a27c11cdeb08e7c2ef4a2c2db225732222706af3c69ebd152ee08d74fc3cd586731ada909e7e8ee7dde2e4ec",
          "sha256": "a8fe3c4bb51374feee9b0f4d6f3009ed60dafa669c7308da6b18633b22129855",
          "sha1": "e3cba774eee7b2d5ef9a56b0d0db01c67ea36829",
          "md5": "109e12dfcd584373d2adc0df333b054c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.7.3-javadoc.jar",
          "url": "android-test-plugin-host-coverage-31.7.3-javadoc.jar",
          "size": 261,
          "sha512": "33aeb239b0eef1a916db4d5c4958e28da67ae3f4034e68b32ac4723dd8b445da59620e06316d572384f2c03423099726b75e93a424c9aeb6a4d83f4f95d5f6b8",
          "sha256": "01439995b8853cf9da6b7d3b2344759e396e55b221875121d62db3c8287b6d2e",
          "sha1": "12ab2becdc67f59ff1f98fb2838c026f3ece141e",
          "md5": "66b7ef74f66808585b536ef77d00e36f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-31.7.3-sources.jar",
          "url": "android-test-plugin-host-coverage-31.7.3-sources.jar",
          "size": 4834,
          "sha512": "4b069eeed28de50cef798c2c5f232a042810f551d36ae62ebd8a0316b72cc26f13b0f13dda3839d33279bb01eae75ad0e046e6b7d42741058367c433d8252f7c",
          "sha256": "85d4531608a1fcfd12fb70f3861f7742a7644f40b57c8f565994fcc4af6c9a49",
          "sha1": "5f38a5e65068ca72090ee5d5dc1ea1523565b29b",
          "md5": "dcc0fb6c5e956b2478ea31ea12b02f93"
        }
      ]
    }
  ]
}
