/**
 * Narration service for LLM-based text preprocessing.
 *
 * Uses Groq (Llama 3.1 8B) to convert article HTML to narration-ready text
 * for text-to-speech. Falls back to simple HTML stripping when Groq is unavailable.
 */

import { createHash } from "crypto";
import Groq from "groq-sdk";
import { z } from "zod";
import { logger } from "@/lib/logger";
import {
  htmlToNarrationInput,
  htmlToPlainText,
  type HtmlToNarrationInputResult,
} from "@/lib/narration/html-to-narration-input";
import { trackNarrationHighlightFallback } from "@/server/metrics";

// Re-export pure functions for backward compatibility
export { htmlToNarrationInput, htmlToPlainText, type HtmlToNarrationInputResult };

/**
 * Schema for a single paragraph from the LLM.
 * Forgiving of id as string or number.
 */
const llmParagraphSchema = z.object({
  id: z
    .union([z.number(), z.string()])
    .transform((val) => (typeof val === "string" ? parseInt(val, 10) : val)),
  text: z
    .string()
    .nullable()
    .transform((val) => val ?? ""),
});

/**
 * Schema for the LLM's structured JSON output.
 */
const llmOutputSchema = z.object({
  paragraphs: z.array(llmParagraphSchema),
});

type LLMOutput = z.infer<typeof llmOutputSchema>;

/**
 * System prompt for the Groq LLM to convert article content to narration-ready text.
 */
export const NARRATION_SYSTEM_PROMPT = `Convert article paragraphs to narration-ready text for text-to-speech.

Transform each paragraph to be TTS-friendly. Return the same structure with matching IDs in the same order.

CRITICAL: One input paragraph → One output paragraph. Do NOT combine or split.

RULES:
- Keep paragraph IDs exactly as provided (as numbers)
- Expand abbreviations: Dr. → Doctor, etc. → et cetera, px → pixels
- Image alt text is already speakable - clean up if needed, don't rephrase
- Skip garbage content (ellipsis, ads, junk) using empty string: "text": ""
- Keep content faithful - do NOT summarize or editorialize
- Add punctuation for natural TTS pauses

INPUT:
{
  "paragraphs": [
    { "id": 0, "text": "Title" },
    { "id": 1, "text": "Dr. Smith said hello." },
    { "id": 2, "text": "Image: diagram showing architecture" },
    { "id": 3, "text": "..." }
  ]
}

OUTPUT:
{
  "paragraphs": [
    { "id": 0, "text": "Title." },
    { "id": 1, "text": "Doctor Smith said hello." },
    { "id": 2, "text": "Image: diagram showing architecture." },
    { "id": 3, "text": "" }
  ]
}

Return ONLY valid JSON.`;

/**
 * Groq client instance. Only initialized when GROQ_API_KEY is set.
 */
let groqClient: Groq | null = null;

/**
 * Gets or creates the Groq client instance.
 * Returns null if GROQ_API_KEY is not set.
 */
function getGroqClient(): Groq | null {
  if (!process.env.GROQ_API_KEY) {
    return null;
  }

  if (!groqClient) {
    groqClient = new Groq({ apiKey: process.env.GROQ_API_KEY });
  }

  return groqClient;
}

/**
 * Computes a SHA-256 hash of the content.
 * Used for deduplication of narration content.
 *
 * @param content - The content to hash
 * @returns Hexadecimal SHA-256 hash string
 *
 * @example
 * const hash = computeContentHash('<p>Hello, world!</p>');
 * // Returns something like "a591a6d40bf..."
 */
export function computeContentHash(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

/**
 * Result of narration generation.
 */
export interface GenerateNarrationResult {
  /** The generated narration text */
  text: string;
  /** Whether this was generated by LLM or fallback */
  source: "llm" | "fallback";
}

/**
 * Generates narration-ready text from HTML content using Groq LLM.
 *
 * Uses structured JSON input/output with per-paragraph fallback.
 * If GROQ_API_KEY is not set or JSON parsing fails, falls back to simple HTML-to-text conversion.
 *
 * @param htmlContent - HTML content to convert to narration
 * @returns Object containing the narration text and source
 * @throws Error if Groq API call fails (caller should handle and use fallback)
 *
 * @example
 * try {
 *   const result = await generateNarration('<p>Hello, Dr. Smith!</p>');
 *   console.log(result.text); // "Hello, Doctor Smith!"
 *   console.log(result.source); // "llm"
 * } catch (error) {
 *   console.error('Groq API failed:', error);
 *   // Use htmlToPlainText as fallback
 * }
 */
export async function generateNarration(htmlContent: string): Promise<GenerateNarrationResult> {
  const client = getGroqClient();

  // Convert HTML to structured paragraphs
  const { paragraphs: inputParagraphs } = htmlToNarrationInput(htmlContent);

  // If Groq is not configured, use fallback
  if (!client) {
    logger.debug("Groq API key not configured, using fallback text conversion");
    trackNarrationHighlightFallback();
    const fallbackText = htmlToPlainText(htmlContent);
    return {
      text: fallbackText,
      source: "fallback",
    };
  }

  try {
    // Send paragraphs as JSON
    const userPrompt = JSON.stringify({ paragraphs: inputParagraphs });

    const response = await client.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages: [
        {
          role: "system",
          content: NARRATION_SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: userPrompt,
        },
      ],
      response_format: { type: "json_object" }, // Request JSON output
      temperature: 0.1, // Low temperature for consistency
      max_tokens: 8000,
    });

    const rawOutput = response.choices[0]?.message?.content;

    if (!rawOutput) {
      logger.warn("Groq returned empty response, using fallback");
      trackNarrationHighlightFallback();
      const fallbackText = htmlToPlainText(htmlContent);
      return {
        text: fallbackText,
        source: "fallback",
      };
    }

    // Parse and validate JSON output
    let llmOutput: LLMOutput;
    try {
      const parsed = JSON.parse(rawOutput);
      llmOutput = llmOutputSchema.parse(parsed);
    } catch (parseError) {
      logger.warn("Failed to parse or validate LLM JSON output, using fallback", {
        error: parseError instanceof Error ? parseError.message : String(parseError),
        rawOutput: rawOutput.substring(0, 200), // Log first 200 chars for debugging
      });
      trackNarrationHighlightFallback();
      const fallbackText = htmlToPlainText(htmlContent);
      return {
        text: fallbackText,
        source: "fallback",
      };
    }

    // Build a Map from LLM output: id → text
    const llmTextMap = new Map<number, string>();
    for (const p of llmOutput.paragraphs) {
      if (!isNaN(p.id)) {
        llmTextMap.set(p.id, p.text);
      }
    }

    // For each input paragraph, look up in LLM output map
    const finalParagraphs: string[] = [];
    for (const inputPara of inputParagraphs) {
      const llmText = llmTextMap.get(inputPara.id);

      if (llmText !== undefined) {
        // Found in LLM output
        if (llmText !== "") {
          // Non-empty text → use it
          finalParagraphs.push(llmText);
        }
        // Empty string → skip (don't include in output)
      } else {
        // Not found or id is NaN → fall back to original input text
        if (inputPara.text !== "") {
          finalParagraphs.push(inputPara.text);
        }
      }
    }

    return {
      text: finalParagraphs.join("\n\n"),
      source: "llm",
    };
  } catch (error) {
    // Log the error and re-throw so caller can handle
    logger.error("Groq API call failed", {
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/**
 * Checks if Groq integration is available.
 *
 * @returns true if GROQ_API_KEY is set
 */
export function isGroqAvailable(): boolean {
  return !!process.env.GROQ_API_KEY;
}
