{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-metadata-3.0.2.jar",
          "url": "ktor-serialization-kotlinx-3.0.2.jar",
          "size": 7797,
          "sha512": "2a916ea6c7edd256090d91987724d9f48e735b0acb12ce0de3e08db2edb63e27a2306606762ba3dfda5bc55999cd9aa7b4533dac38db69bc0fbf73ffbe841edb",
          "sha256": "4f3283d9ff2d0c377a381b11125d6ec27e00ffe9779f390d465810fa9e26b832",
          "sha1": "72be25eedd5c6710c5b4c954ecc9fc02ffc84b31",
          "md5": "7c9d20e5b9a36fd6141f8bd55cd37248"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-kotlin-3.0.2-sources.jar",
          "url": "ktor-serialization-kotlinx-3.0.2-sources.jar",
          "size": 7702,
          "sha512": "e85ca56d5d04a906f9306fa78f637893b54606e0e88725f238c326988982b5e89590a6fa9aa044a82a08f70d8e0c0a5a92dff711fb49068d7f464432cc813f15",
          "sha256": "3633aa3f8d9f339cb22829f9dfa58c4cabd346de00a76e5c0f460cf3c5e35699",
          "sha1": "81f7f5d5140ef8774dffa189672724472c2541fb",
          "md5": "3271c1053bed33e64b7d49303a058b2b"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativearm32/3.0.2/ktor-serialization-kotlinx-androidnativearm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativearm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativearm32/3.0.2/ktor-serialization-kotlinx-androidnativearm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativearm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativearm64/3.0.2/ktor-serialization-kotlinx-androidnativearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativearm64/3.0.2/ktor-serialization-kotlinx-androidnativearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativex64/3.0.2/ktor-serialization-kotlinx-androidnativex64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativex64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativex64/3.0.2/ktor-serialization-kotlinx-androidnativex64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativex64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativex86/3.0.2/ktor-serialization-kotlinx-androidnativex86-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativex86",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-androidnativex86/3.0.2/ktor-serialization-kotlinx-androidnativex86-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-androidnativex86",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosarm64/3.0.2/ktor-serialization-kotlinx-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosarm64/3.0.2/ktor-serialization-kotlinx-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosarm64/3.0.2/ktor-serialization-kotlinx-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iossimulatorarm64/3.0.2/ktor-serialization-kotlinx-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iossimulatorarm64/3.0.2/ktor-serialization-kotlinx-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iossimulatorarm64/3.0.2/ktor-serialization-kotlinx-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosx64/3.0.2/ktor-serialization-kotlinx-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosx64/3.0.2/ktor-serialization-kotlinx-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-iosx64/3.0.2/ktor-serialization-kotlinx-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-js/3.0.2/ktor-serialization-kotlinx-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-js/3.0.2/ktor-serialization-kotlinx-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-js/3.0.2/ktor-serialization-kotlinx-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-jvm/3.0.2/ktor-serialization-kotlinx-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-jvm/3.0.2/ktor-serialization-kotlinx-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-jvm/3.0.2/ktor-serialization-kotlinx-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-linuxarm64/3.0.2/ktor-serialization-kotlinx-linuxarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-linuxarm64/3.0.2/ktor-serialization-kotlinx-linuxarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-linuxx64/3.0.2/ktor-serialization-kotlinx-linuxx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-linuxx64/3.0.2/ktor-serialization-kotlinx-linuxx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosarm64/3.0.2/ktor-serialization-kotlinx-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosarm64/3.0.2/ktor-serialization-kotlinx-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosarm64/3.0.2/ktor-serialization-kotlinx-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosx64/3.0.2/ktor-serialization-kotlinx-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosx64/3.0.2/ktor-serialization-kotlinx-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-macosx64/3.0.2/ktor-serialization-kotlinx-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-mingwx64/3.0.2/ktor-serialization-kotlinx-mingwx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-mingwx64/3.0.2/ktor-serialization-kotlinx-mingwx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosarm64/3.0.2/ktor-serialization-kotlinx-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosarm64/3.0.2/ktor-serialization-kotlinx-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosarm64/3.0.2/ktor-serialization-kotlinx-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvossimulatorarm64/3.0.2/ktor-serialization-kotlinx-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvossimulatorarm64/3.0.2/ktor-serialization-kotlinx-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvossimulatorarm64/3.0.2/ktor-serialization-kotlinx-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosx64/3.0.2/ktor-serialization-kotlinx-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosx64/3.0.2/ktor-serialization-kotlinx-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-tvosx64/3.0.2/ktor-serialization-kotlinx-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-wasm-js/3.0.2/ktor-serialization-kotlinx-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-wasm-js/3.0.2/ktor-serialization-kotlinx-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-wasm-js/3.0.2/ktor-serialization-kotlinx-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm32/3.0.2/ktor-serialization-kotlinx-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm32/3.0.2/ktor-serialization-kotlinx-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm32/3.0.2/ktor-serialization-kotlinx-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm64/3.0.2/ktor-serialization-kotlinx-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm64/3.0.2/ktor-serialization-kotlinx-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosarm64/3.0.2/ktor-serialization-kotlinx-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosdevicearm64/3.0.2/ktor-serialization-kotlinx-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosdevicearm64/3.0.2/ktor-serialization-kotlinx-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosdevicearm64/3.0.2/ktor-serialization-kotlinx-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchossimulatorarm64/3.0.2/ktor-serialization-kotlinx-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchossimulatorarm64/3.0.2/ktor-serialization-kotlinx-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchossimulatorarm64/3.0.2/ktor-serialization-kotlinx-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosx64/3.0.2/ktor-serialization-kotlinx-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosx64/3.0.2/ktor-serialization-kotlinx-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-watchosx64/3.0.2/ktor-serialization-kotlinx-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-watchosx64",
        "version": "3.0.2"
      }
    }
  ]
}
