{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-metadata-3.0.2.jar",
          "url": "ktor-client-content-negotiation-3.0.2.jar",
          "size": 6556,
          "sha512": "1ce42c836a2166cfbac895864d85e372dcf1d468952bf9f3499523bdd5242b253855d8b49db46c7c87d5cf285ac594b9c205f14242a60defbfa926c713b38652",
          "sha256": "a2bbf9abe00ac7d8cda970cedcdf870e387e7211bfb6a03f1b2aa31f839d554e",
          "sha1": "424d3cecbfea3aaefb6376e286f95f160c220981",
          "md5": "a03945a4de52776666a05f962d129ff0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-kotlin-3.0.2-sources.jar",
          "url": "ktor-client-content-negotiation-3.0.2-sources.jar",
          "size": 5283,
          "sha512": "3da8641133e2cedc1796227902543c9b3ebc0b15e3de3a90e2e9642007071cb244e29af6668f9a618c077d325f79513ff8863c8890806070dc65a935ca5c6ed4",
          "sha256": "2606facc3fe159c03a7fb91360fe7603a93c889964d547c18a19a3d88d2932c6",
          "sha1": "5a4b80b8689c851da32bc47a0b905e7a3cf4523c",
          "md5": "9448d8e68bb2257afbb0b9ff8f7715df"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativearm32/3.0.2/ktor-client-content-negotiation-androidnativearm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativearm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativearm32/3.0.2/ktor-client-content-negotiation-androidnativearm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativearm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativearm64/3.0.2/ktor-client-content-negotiation-androidnativearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativearm64/3.0.2/ktor-client-content-negotiation-androidnativearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativex64/3.0.2/ktor-client-content-negotiation-androidnativex64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativex64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativex64/3.0.2/ktor-client-content-negotiation-androidnativex64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativex64",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativex86/3.0.2/ktor-client-content-negotiation-androidnativex86-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativex86",
        "version": "3.0.2"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-androidnativex86/3.0.2/ktor-client-content-negotiation-androidnativex86-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-androidnativex86",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/3.0.2/ktor-client-content-negotiation-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/3.0.2/ktor-client-content-negotiation-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/3.0.2/ktor-client-content-negotiation-iosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/3.0.2/ktor-client-content-negotiation-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/3.0.2/ktor-client-content-negotiation-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/3.0.2/ktor-client-content-negotiation-iossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/3.0.2/ktor-client-content-negotiation-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/3.0.2/ktor-client-content-negotiation-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/3.0.2/ktor-client-content-negotiation-iosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/3.0.2/ktor-client-content-negotiation-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/3.0.2/ktor-client-content-negotiation-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/3.0.2/ktor-client-content-negotiation-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/3.0.2/ktor-client-content-negotiation-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/3.0.2/ktor-client-content-negotiation-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/3.0.2/ktor-client-content-negotiation-jvm-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxarm64/3.0.2/ktor-client-content-negotiation-linuxarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxarm64/3.0.2/ktor-client-content-negotiation-linuxarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxx64/3.0.2/ktor-client-content-negotiation-linuxx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxx64/3.0.2/ktor-client-content-negotiation-linuxx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/3.0.2/ktor-client-content-negotiation-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/3.0.2/ktor-client-content-negotiation-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/3.0.2/ktor-client-content-negotiation-macosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/3.0.2/ktor-client-content-negotiation-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/3.0.2/ktor-client-content-negotiation-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/3.0.2/ktor-client-content-negotiation-macosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-mingwx64/3.0.2/ktor-client-content-negotiation-mingwx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-mingwx64/3.0.2/ktor-client-content-negotiation-mingwx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/3.0.2/ktor-client-content-negotiation-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/3.0.2/ktor-client-content-negotiation-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/3.0.2/ktor-client-content-negotiation-tvosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/3.0.2/ktor-client-content-negotiation-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/3.0.2/ktor-client-content-negotiation-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/3.0.2/ktor-client-content-negotiation-tvossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/3.0.2/ktor-client-content-negotiation-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/3.0.2/ktor-client-content-negotiation-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/3.0.2/ktor-client-content-negotiation-tvosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-wasm-js/3.0.2/ktor-client-content-negotiation-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-wasm-js/3.0.2/ktor-client-content-negotiation-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-wasm-js/3.0.2/ktor-client-content-negotiation-wasm-js-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/3.0.2/ktor-client-content-negotiation-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/3.0.2/ktor-client-content-negotiation-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/3.0.2/ktor-client-content-negotiation-watchosarm32-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/3.0.2/ktor-client-content-negotiation-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/3.0.2/ktor-client-content-negotiation-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/3.0.2/ktor-client-content-negotiation-watchosarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosdevicearm64/3.0.2/ktor-client-content-negotiation-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosdevicearm64/3.0.2/ktor-client-content-negotiation-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosdevicearm64/3.0.2/ktor-client-content-negotiation-watchosdevicearm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosdevicearm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/3.0.2/ktor-client-content-negotiation-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/3.0.2/ktor-client-content-negotiation-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/3.0.2/ktor-client-content-negotiation-watchossimulatorarm64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/3.0.2/ktor-client-content-negotiation-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/3.0.2/ktor-client-content-negotiation-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/3.0.2/ktor-client-content-negotiation-watchosx64-3.0.2.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "3.0.2"
      }
    }
  ]
}
