{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-mock/3.0.2/ktor-client-mock-3.0.2.module",
    "group": "io.ktor",
    "module": "ktor-client-mock",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-mock-jvm-3.0.2.jar",
          "url": "ktor-client-mock-jvm-3.0.2.jar",
          "size": 19515,
          "sha512": "58f5861629a9da79eb2f62c8067909532b527ef6c333ef8e1d14fff3e24b11577ab4f42d42325763d26fe45d73999bfc32f7d8e5d901dd6f639859ae0a69eede",
          "sha256": "cb9289c818b59a83810865ec1236fcbe97c48d5926c16fd8c53c09e7afc4165d",
          "sha1": "62dbb0cf068058c6d0da4897ef2e02797d9b9d5d",
          "md5": "fa89ccbbfe303212dfdfae5c05f100bb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-mock-jvm-3.0.2.jar",
          "url": "ktor-client-mock-jvm-3.0.2.jar",
          "size": 19515,
          "sha512": "58f5861629a9da79eb2f62c8067909532b527ef6c333ef8e1d14fff3e24b11577ab4f42d42325763d26fe45d73999bfc32f7d8e5d901dd6f639859ae0a69eede",
          "sha256": "cb9289c818b59a83810865ec1236fcbe97c48d5926c16fd8c53c09e7afc4165d",
          "sha1": "62dbb0cf068058c6d0da4897ef2e02797d9b9d5d",
          "md5": "fa89ccbbfe303212dfdfae5c05f100bb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-mock-jvm-3.0.2-sources.jar",
          "url": "ktor-client-mock-jvm-3.0.2-sources.jar",
          "size": 4123,
          "sha512": "077281c3977d75f15e68c683110dc67bd0eb2f6b68975bbca873e0fbd1947ceabb415ae547a29639bf7a6cdb38161ef097948cc265a80e3c93a146518de2161d",
          "sha256": "6a1eebde60bf3a1a33a9a8b74cb58c0e153932df04c5b74876278c4348d859f0",
          "sha1": "23ce93a63c62dc59f2622e88a8de1b98215759cd",
          "md5": "37629ccc04ef6da52e99de200b060887"
        }
      ]
    }
  ]
}
