/**
 * SummaryCard Component
 *
 * Displays an AI-generated summary in a collapsible card.
 * Shown at the top of entry content when a summary is available.
 */

"use client";

import { useEntryTextStyles } from "@/lib/appearance/AppearanceProvider";
import { CloseIcon, SparklesIcon, SpinnerIcon } from "@/components/ui/icon-button";

/**
 * Format a date for display.
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

/**
 * Props for the SummaryCard component.
 */
export interface SummaryCardProps {
  /** The summary HTML to display (already converted from Markdown on server) */
  summary: string;
  /** The model ID used for generation */
  modelId: string;
  /** When the summary was generated (null if not yet generated) */
  generatedAt: Date | null;
  /** Whether the summary is currently being generated */
  isLoading?: boolean;
  /** Error message if generation failed */
  error?: string | null;
  /** Callback when regenerate button is clicked */
  onRegenerate?: () => void;
  /** Callback when close button is clicked */
  onClose?: () => void;
}

/**
 * SummaryCard displays an AI-generated summary in a collapsible card.
 */
export function SummaryCard({
  summary,
  modelId,
  generatedAt,
  isLoading = false,
  error = null,
  onRegenerate,
  onClose,
}: SummaryCardProps) {
  const { style } = useEntryTextStyles();

  // Show loading state
  if (isLoading) {
    return (
      <div className="mb-6 rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-900/20">
        <div className="flex items-center gap-3">
          <SparklesIcon className="h-5 w-5 animate-pulse text-blue-600 dark:text-blue-400" />
          <span className="ui-text-sm font-medium text-blue-900 dark:text-blue-100">
            Generating summary...
          </span>
          <SpinnerIcon className="h-4 w-4 text-blue-600 dark:text-blue-400" />
        </div>
      </div>
    );
  }

  // Show error state
  if (error) {
    return (
      <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 dark:border-red-800 dark:bg-red-900/20">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <SparklesIcon className="h-5 w-5 text-red-600 dark:text-red-400" />
            <span className="ui-text-sm font-medium text-red-900 dark:text-red-100">
              Summary generation failed
            </span>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="rounded p-1 text-red-600 hover:bg-red-100 dark:text-red-400 dark:hover:bg-red-800/50"
              aria-label="Close"
            >
              <CloseIcon className="h-4 w-4" />
            </button>
          )}
        </div>
        <p className="ui-text-sm mt-2 text-red-700 dark:text-red-300">{error}</p>
        {onRegenerate && (
          <button
            onClick={onRegenerate}
            className="ui-text-sm mt-3 font-medium text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
          >
            Try again
          </button>
        )}
      </div>
    );
  }

  // Show summary
  return (
    <div className="mb-6 rounded-lg border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-900/20">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <SparklesIcon className="h-5 w-5 text-blue-600 dark:text-blue-400" />
          <span className="ui-text-sm font-medium text-blue-900 dark:text-blue-100">
            AI Summary
          </span>
        </div>
        <div className="flex items-center gap-1">
          {onClose && (
            <button
              onClick={onClose}
              className="rounded p-1 text-blue-600 hover:bg-blue-100 dark:text-blue-400 dark:hover:bg-blue-800/50"
              aria-label="Close summary"
            >
              <CloseIcon className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      {/* Content */}
      <div
        className="prose prose-blue dark:prose-invert mt-3 max-w-none text-blue-900 dark:text-blue-100 [&_a]:text-blue-700 dark:[&_a]:text-blue-300 [&_li]:my-0 [&_ol]:my-1 [&_ul]:my-1"
        style={style}
        dangerouslySetInnerHTML={{ __html: summary }}
      />

      {/* Footer */}
      <div className="ui-text-xs mt-3 flex items-center justify-between text-blue-600 dark:text-blue-400">
        <span>
          Generated by {modelId.replace("claude-", "Claude ").replace(/-/g, " ")}
          {generatedAt && ` on ${formatDate(generatedAt)}`}
        </span>
        {onRegenerate && (
          <button
            onClick={onRegenerate}
            className="font-medium hover:text-blue-700 dark:hover:text-blue-300"
          >
            Regenerate
          </button>
        )}
      </div>
    </div>
  );
}
