/**
 * SummaryCard Component
 *
 * Displays an AI-generated summary in a collapsible card.
 * Shown at the top of entry content when a summary is available.
 */

"use client";

import { useEntryTextStyles } from "@/lib/appearance/AppearanceProvider";
import { CloseIcon, SparklesIcon, SpinnerIcon } from "@/components/ui/icon-button";

/**
 * Format a date for display.
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

/**
 * Props for the SummaryCard component.
 */
export interface SummaryCardProps {
  /** The summary HTML to display (already converted from Markdown on server) */
  summary: string;
  /** The model ID used for generation */
  modelId: string;
  /** When the summary was generated (null if not yet generated) */
  generatedAt: Date | null;
  /** Whether the summary is currently being generated */
  isLoading?: boolean;
  /** Error message if generation failed */
  error?: string | null;
  /** Callback when regenerate button is clicked */
  onRegenerate?: () => void;
  /** Callback when close button is clicked */
  onClose?: () => void;
}

/**
 * SummaryCard displays an AI-generated summary in a collapsible card.
 */
export function SummaryCard({
  summary,
  modelId,
  generatedAt,
  isLoading = false,
  error = null,
  onRegenerate,
  onClose,
}: SummaryCardProps) {
  const { style } = useEntryTextStyles();

  // Show loading state
  if (isLoading) {
    return (
      <div className="border-info-border bg-info-subtle mb-6 rounded-lg border p-4">
        <div className="flex items-center gap-3">
          <SparklesIcon className="text-info h-5 w-5 animate-pulse" />
          <span className="ui-text-sm text-info-subtle-foreground font-medium">
            Generating summary...
          </span>
          <SpinnerIcon className="text-info h-4 w-4" />
        </div>
      </div>
    );
  }

  // Show error state
  if (error) {
    return (
      <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 dark:border-red-800 dark:bg-red-900/20">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <SparklesIcon className="h-5 w-5 text-red-600 dark:text-red-400" />
            <span className="ui-text-sm font-medium text-red-900 dark:text-red-100">
              Summary generation failed
            </span>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="rounded p-1 text-red-600 hover:bg-red-100 dark:text-red-400 dark:hover:bg-red-800/50"
              aria-label="Close"
            >
              <CloseIcon className="h-4 w-4" />
            </button>
          )}
        </div>
        <p className="ui-text-sm mt-2 text-red-700 dark:text-red-300">{error}</p>
        {onRegenerate && (
          <button
            onClick={onRegenerate}
            className="ui-text-sm mt-3 font-medium text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
          >
            Try again
          </button>
        )}
      </div>
    );
  }

  // Show summary
  return (
    <div className="border-info-border bg-info-subtle mb-6 rounded-lg border p-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <SparklesIcon className="text-info h-5 w-5" />
          <span className="ui-text-sm text-info-subtle-foreground font-medium">AI Summary</span>
        </div>
        <div className="flex items-center gap-1">
          {onClose && (
            <button
              onClick={onClose}
              className="text-info hover:bg-info-subtle/50 rounded p-1"
              aria-label="Close summary"
            >
              <CloseIcon className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      {/* Content */}
      <div
        className="prose dark:prose-invert text-info-subtle-foreground [&_a]:text-info-foreground mt-3 max-w-none [&_li]:my-0 [&_ol]:my-1 [&_ul]:my-1"
        style={style}
        dangerouslySetInnerHTML={{ __html: summary }}
      />

      {/* Footer */}
      <div className="ui-text-xs text-info mt-3 flex items-center justify-between">
        <span>
          Generated by {modelId.replace("claude-", "Claude ").replace(/-/g, " ")}
          {generatedAt && ` on ${formatDate(generatedAt)}`}
        </span>
        {onRegenerate && (
          <button onClick={onRegenerate} className="font-medium hover:opacity-80">
            Regenerate
          </button>
        )}
      </div>
    </div>
  );
}
