{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-io-core/0.5.4/kotlinx-io-core-0.5.4.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-io-core",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.5.4.jar",
          "url": "kotlinx-io-core-jvm-0.5.4.jar",
          "size": 150544,
          "sha512": "a106e51ba8d5e90ac1985d36977b0d9e044c4dd6539ffd84b764675a7f25ebc4f9f8e7b512f7d9ce68185d485ad8b0d22d843204ffd90c26729da07ee434f846",
          "sha256": "dc3587c12795af01231591c0ef09a4139dfca8113c2989273b96b958006853c3",
          "sha1": "16566a36d64d88af421fbee163eeeb6aa6406a43",
          "md5": "77eaec237e1fc959491be09260203711"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.5.4.jar",
          "url": "kotlinx-io-core-jvm-0.5.4.jar",
          "size": 150544,
          "sha512": "a106e51ba8d5e90ac1985d36977b0d9e044c4dd6539ffd84b764675a7f25ebc4f9f8e7b512f7d9ce68185d485ad8b0d22d843204ffd90c26729da07ee434f846",
          "sha256": "dc3587c12795af01231591c0ef09a4139dfca8113c2989273b96b958006853c3",
          "sha1": "16566a36d64d88af421fbee163eeeb6aa6406a43",
          "md5": "77eaec237e1fc959491be09260203711"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-io-core-jvm-0.5.4-sources.jar",
          "url": "kotlinx-io-core-jvm-0.5.4-sources.jar",
          "size": 76930,
          "sha512": "c29d8b64c51bd2dd6eab0b05853f9ded22b68885ddb32292aca487de2d427ac7a0fdf102a8586c563e02ebc4314539cdc08ca39209efcb1c48bde9cd2933c775",
          "sha256": "fa48baf82c3b07173f09004e7003239128a6a375bb08b71191d0b7d032e1e1d6",
          "sha1": "6858a52345a0687ba5ef5abc20279e2e8522068d",
          "md5": "edf1ed35b97b94b45d0f1ae10bf4a911"
        }
      ]
    }
  ]
}
