/**
 * Schema dump script that exports the current database schema to a file.
 *
 * Usage: pnpm db:schema
 *
 * This script:
 * 1. Runs pg_dump --schema-only to get the current schema
 * 2. Excludes the drizzle migration tracking schema in Postgres (internal)
 * 3. Outputs a consistent, reproducible SQL file
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const OUTPUT_FILE = path.join(process.cwd(), "migrations", "schema.sql");

/**
 * Cleans up pg_dump output by removing unnecessary lines:
 * - Comment lines (-- ...)
 * - \restrict / \unrestrict commands
 * - Session settings that aren't migration-controlled
 * - Excessive blank lines
 */
function cleanupSchema(schema: string): string {
  const lines = schema.split("\n");
  const cleanedLines: string[] = [];

  // Session settings to remove (not migration-controlled)
  const sessionSettingsToRemove = new Set([
    "SET statement_timeout",
    "SET lock_timeout",
    "SET idle_in_transaction_session_timeout",
    "SET transaction_timeout",
    "SET client_encoding",
    "SET standard_conforming_strings",
    "SELECT pg_catalog.set_config",
    "SET check_function_bodies",
    "SET xmloption",
    "SET client_min_messages",
    "SET row_security",
    "SET default_table_access_method",
  ]);

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comment lines
    if (trimmed.startsWith("--")) {
      continue;
    }

    // Skip \restrict and \unrestrict commands
    if (trimmed.startsWith("\\restrict") || trimmed.startsWith("\\unrestrict")) {
      continue;
    }

    // Skip session settings
    const isSessionSetting = Array.from(sessionSettingsToRemove).some((prefix) =>
      trimmed.startsWith(prefix)
    );
    if (isSessionSetting) {
      continue;
    }

    cleanedLines.push(line);
  }

  // Collapse multiple consecutive blank lines into single blank lines
  let result = cleanedLines.join("\n");
  result = result.replace(/\n{3,}/g, "\n\n");
  result = result.trim() + "\n";

  return result;
}

function parseConnectionString(url: string): {
  host: string;
  port: string;
  database: string;
  user: string;
  password?: string;
} {
  const parsed = new URL(url);
  return {
    host: parsed.hostname,
    port: parsed.port || "5432",
    database: parsed.pathname.slice(1), // Remove leading /
    user: parsed.username,
    password: parsed.password || undefined,
  };
}

/**
 * Dumps the current database schema to migrations/schema.sql
 * @param databaseUrl - PostgreSQL connection string
 */
export function dumpSchema(databaseUrl: string): void {
  console.log("Dumping database schema...");

  const conn = parseConnectionString(databaseUrl);

  // Build pg_dump command with options for consistent, reproducible output
  const pgDumpArgs = [
    "pg_dump",
    "--schema-only", // Only dump schema, not data
    "--no-owner", // Don't include ownership commands
    "--no-privileges", // Don't include privilege commands (GRANT/REVOKE)
    "--no-tablespaces", // Don't include tablespace assignments
    "--no-comments", // Skip comments that might vary
    "--exclude-schema=drizzle", // Exclude drizzle's internal migration tracking schema
    `--host=${conn.host}`,
    `--port=${conn.port}`,
    `--username=${conn.user}`,
    conn.database,
  ];

  // Set up environment with password
  const env = { ...process.env };
  if (conn.password) {
    env.PGPASSWORD = conn.password;
  }

  const schema = execSync(pgDumpArgs.join(" "), {
    encoding: "utf-8",
    env,
    maxBuffer: 10 * 1024 * 1024, // 10MB buffer for large schemas
  });

  // Clean up the schema output
  const cleanedSchema = cleanupSchema(schema);

  // Add header comment
  const header = `--
-- Lion Reader Database Schema
-- Generated by: pnpm db:schema
--
-- This file is auto-generated from the current database state.
-- It provides a snapshot of the schema for reference and review.
-- Do not edit manually - changes should be made via migrations.
--

`;

  fs.writeFileSync(OUTPUT_FILE, header + cleanedSchema);

  console.log(`✓ Schema dumped to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

// Run directly if this is the main module
if (require.main === module) {
  const databaseUrl = process.env.DATABASE_URL;

  if (!databaseUrl) {
    console.error("DATABASE_URL environment variable is not set");
    process.exit(1);
  }

  try {
    dumpSchema(databaseUrl);
  } catch (error) {
    if (error instanceof Error && "stderr" in error) {
      console.error("pg_dump failed:", (error as { stderr: string }).stderr);
    } else {
      console.error("pg_dump failed:", error);
    }
    process.exit(1);
  }
}
