/**
 * Schema dump script that exports the current database schema to a file.
 *
 * Usage: pnpm db:schema
 *
 * This script:
 * 1. Runs pg_dump --schema-only to get the current schema
 * 2. Excludes the drizzle migration tracking schema (internal)
 * 3. Outputs a consistent, reproducible SQL file
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const OUTPUT_FILE = path.join(process.cwd(), "drizzle", "schema.sql");

function parseConnectionString(url: string): {
  host: string;
  port: string;
  database: string;
  user: string;
  password?: string;
} {
  const parsed = new URL(url);
  return {
    host: parsed.hostname,
    port: parsed.port || "5432",
    database: parsed.pathname.slice(1), // Remove leading /
    user: parsed.username,
    password: parsed.password || undefined,
  };
}

/**
 * Dumps the current database schema to drizzle/schema.sql
 * @param databaseUrl - PostgreSQL connection string
 */
export function dumpSchema(databaseUrl: string): void {
  console.log("Dumping database schema...");

  const conn = parseConnectionString(databaseUrl);

  // Build pg_dump command with options for consistent, reproducible output
  const pgDumpArgs = [
    "pg_dump",
    "--schema-only", // Only dump schema, not data
    "--no-owner", // Don't include ownership commands
    "--no-privileges", // Don't include privilege commands (GRANT/REVOKE)
    "--no-tablespaces", // Don't include tablespace assignments
    "--no-comments", // Skip comments that might vary
    "--exclude-schema=drizzle", // Exclude drizzle's internal migration tracking schema
    `--host=${conn.host}`,
    `--port=${conn.port}`,
    `--username=${conn.user}`,
    conn.database,
  ];

  // Set up environment with password
  const env = { ...process.env };
  if (conn.password) {
    env.PGPASSWORD = conn.password;
  }

  const schema = execSync(pgDumpArgs.join(" "), {
    encoding: "utf-8",
    env,
    maxBuffer: 10 * 1024 * 1024, // 10MB buffer for large schemas
  });

  // Add header comment
  const header = `--
-- Lion Reader Database Schema
-- Generated by: pnpm db:schema
--
-- This file is auto-generated from the current database state.
-- It provides a snapshot of the schema for reference and review.
-- Do not edit manually - changes should be made via migrations.
--

`;

  fs.writeFileSync(OUTPUT_FILE, header + schema);

  console.log(`✓ Schema dumped to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

// Run directly if this is the main module
if (require.main === module) {
  const databaseUrl = process.env.DATABASE_URL;

  if (!databaseUrl) {
    console.error("DATABASE_URL environment variable is not set");
    process.exit(1);
  }

  try {
    dumpSchema(databaseUrl);
  } catch (error) {
    if (error instanceof Error && "stderr" in error) {
      console.error("pg_dump failed:", (error as { stderr: string }).stderr);
    } else {
      console.error("pg_dump failed:", error);
    }
    process.exit(1);
  }
}
