/**
 * Bundles the native app's reader-view narration script
 * (`src/lib/narration/app-reader.ts`) from the web's narration code, so the
 * app numbers and speaks articles exactly as the web does. Regenerate with
 * `pnpm app:narration`; a unit test fails when the committed copy is stale.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildSync } from "esbuild";

export const APP_NARRATION_PATH = "kmp/androidApp/src/main/assets/reader/narration.js";

export function renderAppNarration(): string {
  const result = buildSync({
    entryPoints: ["src/lib/narration/app-reader.ts"],
    bundle: true,
    format: "iife",
    // The WebView is evergreen Chromium; keep the output readable.
    target: "chrome100",
    minify: false,
    legalComments: "none",
    write: false,
  });
  return `// Generated by scripts/export-app-narration.ts (pnpm app:narration); do not edit.\n${result.outputFiles[0].text}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(APP_NARRATION_PATH, renderAppNarration());
  console.log(`Wrote ${APP_NARRATION_PATH}`);
}
