#!/usr/bin/env bash
#
# Start throwaway Postgres + Redis on random ports, with no Docker required.
#
# Intended for environments where `docker compose` and the shared dev databases
# aren't reliably available (e.g. sandboxed AI agents). It spins up a fresh
# Postgres cluster and a Redis instance using the native binaries, on random
# free ports, runs migrations, writes two gitignored env files
# (`.env.local-services` for the dev app, `.env.local-services.test` for tests),
# and then blocks. Everything is torn down when this process exits.
#
# Usage (run as a BACKGROUND task so it's cleaned up when your session ends):
#
#   pnpm services          # equivalently: bash scripts/local-services.sh
#
# Then, in the foreground:
#
#   pnpm test:integration:local
#   pnpm test:e2e:local
#   PORT=<random> pnpm dev:local     # then open http://<host>:<PORT>
#
# See CLAUDE.md ("Local Services (no Docker)") for details.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ENV_DEV="$REPO_ROOT/.env.local-services"
ENV_TEST="$REPO_ROOT/.env.local-services.test"

PG_USER="lionreader"
PG_PASSWORD="lionreader"
DEV_DB="lionreader"
TEST_DB="lionreader_test"

# --- Locate binaries -------------------------------------------------------

# Prefer the newest installed Postgres (Debian/Ubuntu layout), fall back to PATH.
PG_BIN=""
for dir in $(ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -rV); do
  if [[ -x "$dir/initdb" && -x "$dir/pg_ctl" ]]; then
    PG_BIN="$dir"
    break
  fi
done
if [[ -z "$PG_BIN" ]] && command -v initdb >/dev/null 2>&1; then
  PG_BIN="$(dirname "$(command -v initdb)")"
fi
if [[ -z "$PG_BIN" ]]; then
  echo "ERROR: could not find Postgres binaries (initdb/pg_ctl)." >&2
  echo "       Install postgresql, or add its bin/ dir to PATH." >&2
  exit 1
fi

REDIS_BIN="$(command -v redis-server || true)"
if [[ -z "$REDIS_BIN" ]]; then
  echo "ERROR: could not find redis-server on PATH." >&2
  exit 1
fi

# --- Scratch state ---------------------------------------------------------

STATE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lion-services.XXXXXX")"
PGDATA="$STATE_DIR/pgdata"
REDIS_PID=""

cleanup() {
  # Ordered fastest-to-slowest so a killed session tears down promptly.
  [[ -n "$REDIS_PID" ]] && kill "$REDIS_PID" 2>/dev/null || true
  "$PG_BIN/pg_ctl" -D "$PGDATA" -m immediate stop >/dev/null 2>&1 || true
  rm -f "$ENV_DEV" "$ENV_TEST"
  rm -rf "$STATE_DIR"
}
trap cleanup EXIT INT TERM

# --- Pick two free ports ---------------------------------------------------

read -r PGPORT REDISPORT < <(python3 - <<'PY'
import socket
def free():
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port
print(free(), free())
PY
)

# --- Start Postgres --------------------------------------------------------

echo "==> Initializing Postgres cluster ($("$PG_BIN/postgres" --version | awk '{print $3}'))"
"$PG_BIN/initdb" -D "$PGDATA" -U "$PG_USER" --auth=trust -E UTF8 >/dev/null

echo "==> Starting Postgres on 127.0.0.1:$PGPORT"
"$PG_BIN/pg_ctl" -D "$PGDATA" \
  -o "-p $PGPORT -k $PGDATA -c listen_addresses=127.0.0.1" \
  -w -l "$STATE_DIR/postgres.log" start >/dev/null

"$PG_BIN/createdb" -h 127.0.0.1 -p "$PGPORT" -U "$PG_USER" "$DEV_DB"
"$PG_BIN/createdb" -h 127.0.0.1 -p "$PGPORT" -U "$PG_USER" "$TEST_DB"

# --- Start Redis -----------------------------------------------------------

echo "==> Starting Redis on 127.0.0.1:$REDISPORT"
"$REDIS_BIN" --port "$REDISPORT" --bind 127.0.0.1 \
  --save '' --appendonly no --dir "$STATE_DIR" \
  >"$STATE_DIR/redis.log" 2>&1 &
REDIS_PID=$!

until redis-cli -h 127.0.0.1 -p "$REDISPORT" ping >/dev/null 2>&1; do
  sleep 0.2
done

# --- Connection strings + env files ----------------------------------------

DEV_URL="postgresql://$PG_USER:$PG_PASSWORD@127.0.0.1:$PGPORT/$DEV_DB"
TEST_URL="postgresql://$PG_USER:$PG_PASSWORD@127.0.0.1:$PGPORT/$TEST_DB"
REDIS_URL="redis://127.0.0.1:$REDISPORT"

# These files are gitignored via the `.env.*` rule. They're layered on top of
# `.env.test` by the *:local pnpm scripts (dotenv -o, so they win), and consumed
# directly by `dev:local`. Removed on exit by cleanup().
cat >"$ENV_DEV" <<EOF
# Auto-generated by scripts/local-services.sh — do not edit, do not commit.
DATABASE_URL=$DEV_URL
REDIS_URL=$REDIS_URL
EOF

cat >"$ENV_TEST" <<EOF
# Auto-generated by scripts/local-services.sh — do not edit, do not commit.
DATABASE_URL=$TEST_URL
REDIS_URL=$REDIS_URL
EOF

# --- Migrate both databases ------------------------------------------------

echo "==> Running migrations (dev + test databases)"
DATABASE_URL="$DEV_URL" REDIS_URL="$REDIS_URL" pnpm exec tsx scripts/migrate.ts >/dev/null
DATABASE_URL="$TEST_URL" REDIS_URL="$REDIS_URL" pnpm exec tsx scripts/migrate.ts >/dev/null

# --- Ready -----------------------------------------------------------------

cat <<EOF

============================================================================
  Local services ready. Leave this task running; it cleans up on exit.
============================================================================
  Postgres : 127.0.0.1:$PGPORT   (user/pass: $PG_USER/$PG_PASSWORD)
  Redis    : $REDIS_URL
  Dev DB   : $DEV_DB      -> .env.local-services
  Test DB  : $TEST_DB -> .env.local-services.test

  Run tests against these services:
    pnpm test:integration:local
    pnpm test:e2e:local

  Run the dev app (pick a random free PORT to avoid conflicts):
    PORT=$(python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()') pnpm dev:local
============================================================================
EOF

# Block until this process is killed (session end / Ctrl-C), then cleanup runs.
while true; do
  sleep 3600 &
  wait $!
done
