{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-cio/3.0.2/ktor-client-cio-3.0.2.module",
    "group": "io.ktor",
    "module": "ktor-client-cio",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.0.2.jar",
          "url": "ktor-client-cio-jvm-3.0.2.jar",
          "size": 110749,
          "sha512": "5a0a278f6dcda524bcd5282b58a8a913e30124b78399ff9b51d271a22d4926a2a2329c0bdc7b283e32d9ff77b92130927a6c2e3a74562780f230332114e1876d",
          "sha256": "977b6a633805ce0f5d0a132311d6276a3b4ab9200a4537c3f1b4f03ba58592b3",
          "sha1": "4691c3f7c250dea1848065519c24e85e3bdf3d10",
          "md5": "dad96c0de485ff21e4392105ac6a0a6f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.0.2.jar",
          "url": "ktor-client-cio-jvm-3.0.2.jar",
          "size": 110749,
          "sha512": "5a0a278f6dcda524bcd5282b58a8a913e30124b78399ff9b51d271a22d4926a2a2329c0bdc7b283e32d9ff77b92130927a6c2e3a74562780f230332114e1876d",
          "sha256": "977b6a633805ce0f5d0a132311d6276a3b4ab9200a4537c3f1b4f03ba58592b3",
          "sha1": "4691c3f7c250dea1848065519c24e85e3bdf3d10",
          "md5": "dad96c0de485ff21e4392105ac6a0a6f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-cio-jvm-3.0.2-sources.jar",
          "url": "ktor-client-cio-jvm-3.0.2-sources.jar",
          "size": 18853,
          "sha512": "b85ba9ffdf32f88fa4f07393450bc49329e7981a9eca7f2b1b38dca39a77a05c249e8eefce469adeac93a211f3f3b7f96097547c2095c35174001cb9869d4d24",
          "sha256": "e1857132c00da1cbe2ee47ff9e5098fe40bd1257d1a1b2793fc917325e017d89",
          "sha1": "169f065d2f14c01dbf1ff181b837edc4baa16fa7",
          "md5": "93886fab0a29a68664885922a0857d8e"
        }
      ]
    }
  ]
}
