{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-ddmlib",
    "version": "31.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.7.3.jar",
          "url": "android-device-provider-ddmlib-31.7.3.jar",
          "size": 62884,
          "sha512": "ffc5b21552df5ee98f7557b954f22f5a1d08e13c453df815f74e7ad8e18b7ac7a85b47528c27accc4f1132156b4850b957392855d6c994235b31bbe130f8ae89",
          "sha256": "60cf666b057a3b3bb5063e29e226e211b8e0cc455a5625cdf898400034f59478",
          "sha1": "f29350d68e4236fa62e82a13f741d4dc90b595ec",
          "md5": "292b51233993bf64122d4fd8ab9a9a66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-profile",
          "version": {
            "requires": "31.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.7.3.jar",
          "url": "android-device-provider-ddmlib-31.7.3.jar",
          "size": 62884,
          "sha512": "ffc5b21552df5ee98f7557b954f22f5a1d08e13c453df815f74e7ad8e18b7ac7a85b47528c27accc4f1132156b4850b957392855d6c994235b31bbe130f8ae89",
          "sha256": "60cf666b057a3b3bb5063e29e226e211b8e0cc455a5625cdf898400034f59478",
          "sha1": "f29350d68e4236fa62e82a13f741d4dc90b595ec",
          "md5": "292b51233993bf64122d4fd8ab9a9a66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.7.3-javadoc.jar",
          "url": "android-device-provider-ddmlib-31.7.3-javadoc.jar",
          "size": 261,
          "sha512": "f717fadf0515e3026d19b0042bc0ba2fe7ba6d73544082c4aeb56855e9d9eeae522ece82aabe78d46f56c47277ffec1affc7f2ef37f376433829ed18df78671d",
          "sha256": "a6046a1de8017d6ccd412c360a5d73c43f38440d778548815deba33b362ba715",
          "sha1": "d1af43f84e4076215374769ffbf74b3c3256d17c",
          "md5": "5f0cb24d8c638b8764c3cb5ba3b27bdc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-ddmlib-31.7.3-sources.jar",
          "url": "android-device-provider-ddmlib-31.7.3-sources.jar",
          "size": 11073,
          "sha512": "d6204c81831ec094c829195c229646e23e51c797f94778b67e35e4eccf8215ac8ddf0f8e09779cc8409e0a2195e795cabf3cf0106b178f35da22b8b9cd83eeeb",
          "sha256": "388e3f400480a3a64c77245ec783548318d85a7f33448fd4dd2f6185fe0bcf9a",
          "sha1": "d2e80db76bd665f79e27f2bd7492bd97efecd309",
          "md5": "79efefa3a4ccfdc0e2fc2bf1b76aac9b"
        }
      ]
    }
  ]
}
