{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.5-sources.jar",
          "url": "navigation-compose-2.8.5-sources.jar",
          "size": 23704,
          "sha512": "3c73ce59907164903ac7a9db831ae8fecd0bd7fa977fdcc63558520cbeb12ad662bb379940f1b44f4620c4bfab8c92bb2eb290a14b78c9b1d37a74b1974a41fd",
          "sha256": "d4a9e92c45df405a22935478eda6e96c23db33fa240c221ea863bd3b475f386e",
          "sha1": "0b301c03402094826cb1ac5d6ff3690d1e79ac3d",
          "md5": "f1ed9d2230c13f9aa5b73d2f72b68be9"
        },
        {
          "name": "navigation-compose-2.8.5-samples-sources.jar",
          "url": "navigation-compose-2.8.5-samples-sources.jar",
          "size": 11296,
          "sha512": "de1a633658a10a834f78203651defdba1b51fc96de5ecbe0308007b0e0e6f502aa7da40acbe0c229330c5f3b413ddf2d3614263eba735c709ce2138e3df53394",
          "sha256": "3e15db75e78018d734ba4839ac0b0ca3b067415af1d5850a2810dcacd73f411e",
          "sha1": "1900b29173e399a9b4584cb84ca2067222fc0517",
          "md5": "3e636d70a85d8e869c462b639a97317a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.5.aar",
          "url": "navigation-compose-2.8.5.aar",
          "size": 1228033,
          "sha512": "6c33cea1e5ebc86cd0269abd67e62d6aa7085229b8bc1e48a766c16c45834e31170c50869141a0cb05c55a921c0b74f3f8f4b3b16abd4ec104c3d858da0dcb50",
          "sha256": "3a8e74dcc9ba2e3c6f3c25e574e75bf4bc30cf9d9e4c7a54c5b3d275e8570333",
          "sha1": "fdb67df4829e9141999151f55d85fd590623ef41",
          "md5": "92778925916eb59d9407164616eb7a2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.5.aar",
          "url": "navigation-compose-2.8.5.aar",
          "size": 1228033,
          "sha512": "6c33cea1e5ebc86cd0269abd67e62d6aa7085229b8bc1e48a766c16c45834e31170c50869141a0cb05c55a921c0b74f3f8f4b3b16abd4ec104c3d858da0dcb50",
          "sha256": "3a8e74dcc9ba2e3c6f3c25e574e75bf4bc30cf9d9e4c7a54c5b3d275e8570333",
          "sha1": "fdb67df4829e9141999151f55d85fd590623ef41",
          "md5": "92778925916eb59d9407164616eb7a2f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.5-versionMetadata.json",
          "url": "navigation-compose-2.8.5-versionMetadata.json",
          "size": 21861,
          "sha512": "218ed78148f08d3585eac7125b54263504279fb9de0312e5bfab6afb718b718745a5bd05f11ae3a56fd6de158511335ea1c4bfde117217ad7ede5ac237f433a4",
          "sha256": "f26cbb6c2b7b99532869cf9b14e78b34fbad85c368b32c915c31620df58b0339",
          "sha1": "3fbcfdb4c448201ab049930fd05103779df3fc93",
          "md5": "12befdbc13cc1c370bb6d3dcbbe9a828"
        }
      ]
    }
  ]
}