import { type DemoArticle } from "./types";

const article: DemoArticle = {
  id: "text-to-speech",
  subscriptionId: "reading-experience",
  type: "web",
  url: "https://github.com/brendanlong/lion-reader/pull/15",
  title: "Text-to-Speech Narration",
  author: null,
  summary:
    "Listen to any article with natural cloud voices or on-device voices, with synchronized paragraph highlighting.",
  publishedAt: new Date("2025-12-27T18:00:00Z"),
  starred: false,
  summaryHtml: `<p>Lion Reader can read articles aloud. <strong>Cloud voices</strong> (Kokoro by default, or your own BreezeBlue/DeepInfra/OpenRouter key) stream audio with minimal setup. <strong>On-device voices</strong> (Piper or browser built-ins) keep audio local. Optional <strong>AI cleanup</strong> rewrites text for smoother listening. Playback supports <strong>paragraph highlighting</strong>, navigation, speed control, and media-key shortcuts.</p>`,
  summaryModelId: "claude-sonnet-5",
  summaryGeneratedAt: new Date("2026-10-02"),
  contentHtml: `
    <p>Sometimes you want to listen instead of read &mdash; while cooking, commuting, or just giving your eyes a rest. Press <strong>Listen</strong> at the top of any article and Lion Reader reads it aloud, highlighting each paragraph as it goes. Try it on this one: the demo reads with Kokoro, the default cloud voice.</p>

    <h3>Cloud Voices</h3>

    <p>Cloud voices are natural-sounding neural voices generated by a speech provider. The default is <a href="https://huggingface.co/hexgrad/Kokoro-82M" target="_blank" rel="noopener noreferrer">Kokoro</a>, a high-quality open voice model, and it needs no API key: just pick Cloud Voices in Settings. If you have a <a href="https://breezeblue.ai/" target="_blank" rel="noopener noreferrer">BreezeBlue</a> API key, add it in Settings to narrate with BreezeBlue&rsquo;s voices instead, including your favorites and voices you&rsquo;ve made yourself. Your own <a href="https://deepinfra.com/" target="_blank" rel="noopener noreferrer">DeepInfra</a> or <a href="https://openrouter.ai/" target="_blank" rel="noopener noreferrer">OpenRouter</a> key unlocks their other speech models too.</p>

    <p>Audio streams to you as it&rsquo;s generated, so narration usually starts within a second or two, and Lion Reader stays about half a minute ahead of where you&rsquo;re listening. Cloud voices keep playing with your screen locked or the app in the background, and you can set how long a pause they leave between passages.</p>

    <h3>On-Device Voices</h3>

    <p>Prefer to keep everything on your device? <strong>Enhanced voices</strong> use <a href="https://github.com/rhasspy/piper" target="_blank" rel="noopener noreferrer">Piper</a>, a neural voice that runs right in your browser. Download one of four voices once (17&ndash;50&nbsp;MB) in Settings, and it works offline; like cloud voices, it keeps playing with the screen locked. Or use your browser&rsquo;s <strong>built-in voices</strong>, which need no setup at all and start instantly, though their quality varies from browser to browser, and some (marked &ldquo;online&rdquo;) are generated on your browser maker&rsquo;s servers.</p>

    <h3>Optional AI Cleanup</h3>

    <p>Some articles don&rsquo;t read well aloud as written: abbreviations, units, and stray formatting can trip up any voice. Turn on <strong>AI text processing</strong> and an AI model rewrites the article for listening first &mdash; &ldquo;Dr. Smith&rdquo; becomes &ldquo;Doctor Smith,&rdquo; &ldquo;5 ms&rdquo; becomes &ldquo;5 milliseconds&rdquo; &mdash; without summarizing or changing its meaning. Because the whole article is processed before narration starts, the first listen takes a little longer; after that it&rsquo;s cached and starts right away. It&rsquo;s off by default.</p>

    <h3>Reading Along</h3>

    <p>As narration plays, Lion Reader highlights the current paragraph and scrolls to keep it in view. Click any paragraph to jump there, skip forward or back a paragraph at a time, and set the speed anywhere from half to double. Narration works with your lock screen, notification shade, headphone buttons, and media keys, and with <a href="/demo/all?entry=keyboard-shortcuts">keyboard shortcuts</a>: <kbd>p</kbd> plays or pauses, and <kbd>Shift</kbd>+<kbd>N</kbd> and <kbd>Shift</kbd>+<kbd>P</kbd> move to the next or previous paragraph.</p>

    <p>With cloud voices, only the text being read is sent to the voice provider, a passage at a time. With on-device voices, nothing leaves your device unless you turn on AI text processing, which sends the article to the AI model first.</p>
  `,
};

export default article;
