{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-replay",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-replay-8.0.0.aar",
          "url": "sentry-android-replay-8.0.0.aar",
          "size": 255164,
          "sha512": "12aa193502a1e42033165ce3f61bda3cba7102566042a1e8151a291ffd23dc453b50b05462a5a8781cb7847e47075316f95a2ed83b8fbdc634eb41a3b2e0e596",
          "sha256": "3651addedc06ec774d86f8503781d8455febee3656f7521a4d82e3344a37cc4a",
          "sha1": "f6ea6af9ce6007980a1bf06548db2c1f1cc16a47",
          "md5": "d79750ede4f9caaf7499b29e408bf026"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-replay-8.0.0.aar",
          "url": "sentry-android-replay-8.0.0.aar",
          "size": 255164,
          "sha512": "12aa193502a1e42033165ce3f61bda3cba7102566042a1e8151a291ffd23dc453b50b05462a5a8781cb7847e47075316f95a2ed83b8fbdc634eb41a3b2e0e596",
          "sha256": "3651addedc06ec774d86f8503781d8455febee3656f7521a4d82e3344a37cc4a",
          "sha1": "f6ea6af9ce6007980a1bf06548db2c1f1cc16a47",
          "md5": "d79750ede4f9caaf7499b29e408bf026"
        }
      ]
    }
  ]
}
